### ISSUE TITLE
Bug: Lisp nesting exceeds ‘max-lisp-eval-depth’

### ISSUE THREAD

**Issue by danielfleischer** [minad/tempel#104]
Recipe:
1. `emacs -Q -L .emacs.d/elpa/tempel-20230510.1659 -L .emacs.d/elpa/compat-29.1.4.1 -l tempel`
2. Insert some template with `(p "HI" var)`
3. Template is inserted but when writing, one get the following error
    `tempel--field-modified: Lisp nesting exceeds ‘max-lisp-eval-depth’`

Emacs 29.0.91, tempel 20230510.1659.

**Comment by minad** [comment]
Thanks, should hopefully be fixed now.
