### ISSUE TITLE
Trigger Code when cursor reaches template point

### ISSUE THREAD

**Issue by fejfighter** [minad/tempel#105]
While working though #101 / https://github.com/fejfighter/eglot-tempel/issues/5

I have found that an lsp server will provide a list of alternate completions for a template (ie `lt` `eq` `gt` etc) 
I'd like to trigger a completion at point when the cursor reaches that point in the template, rather than when the template is initially inserted,
I'm not sure if that is currently supported

**Comment by minad** [comment]
This feature is not supported, but there is a tempel--enter feature which can be used to run some code when the user moves to a field.

**Comment by minad** [comment]
Closing. I don't plan to add this feature right now. 

To support this we could generalize `tempel-user-elements` such that the hooks receive the current Tempel state as argument. Then one could define custom elements, which set the property `tempel--enter`. The function `tempel--enter` is executed when moving to a field.
