### ISSUE TITLE
Error when undo-ing after template insertion

### ISSUE THREAD

**Issue by fast-90** [minad/tempel#107]
Hi Daniel,

Just wanted to report something I just came across.

I have the following template:

```emacs-lisp
markdown-mode

(py "```{python}" n p n "```")
```

When I type `<py TAB`, it inserts the template as expected with my config (see also below). Thereafter, I `undo` with `C-x u` immediately after inserting the template (that is, I haven't filed in the resulting template which was inserted) until the original state before inserting the template. Now if I try to insert the same template again, I get the following error:

```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  tempel--insert(("```{python}" n p n "```") nil)
  tempel--exit(((py "```{python}" n p n "```")) nil "py" finished)
  apply(tempel--exit (((py "```{python}" n p n "```")) nil "py" finished))
  #f(compiled-function (&rest args2) #<bytecode -0x14cb0e799957b7bf>)("py" finished)
  corfu--done("py" finished)
  corfu-complete()
  funcall-interactively(corfu-complete)
  command-execute(corfu-complete)
```

I use plain vanilla Emacs `undo`, so no undo-tree or undo-fu etc.

My corfu and tempel config are as follows:

```emacs-lisp
(use-package corfu
  :bind (:map corfu-map
         ("C-j" . corfu-next)
         ("C-k" . corfu-previous)
         ("TAB" . corfu-insert)
         ("RET" . nil)
         :map org-mode-map
         ("C-," . nil))
  :custom
  (corfu-cycle t)
  (corfu-auto t)
  (corfu-on-exact-match nil)
  :init
  (global-corfu-mode)
  (global-set-key (kbd "M-i") #'completion-at-point))

(use-package tempel
  :init
  (defun tempel-setup-capf ()
    (setq-local completion-at-point-functions
                (cons #'tempel-complete
                      completion-at-point-functions)))
  (add-hook 'conf-mode-hook 'tempel-setup-capf)
  (add-hook 'prog-mode-hook 'tempel-setup-capf)
  (add-hook 'text-mode-hook 'tempel-setup-capf)
  (add-hook 'eglot-managed-mode-hook 'tempel-setup-capf)
  (setq tempel-trigger-prefix "<"))
```

Not sure if there is anything wrong with my setup?

**Comment by minad** [comment]
Hi, thanks for the report. Unfortunately I cannot reproduce this, so this may be caused by some interaction in your configuration. Are you sure that you use the newest versions of all involved packages? Can you reproduce this also in emacs -Q?

**Comment by fast-90** [comment]
Ah I should have tried out `emacs -Q` first of course!

You were absolutely right, the culprit for me was `poly-markdown`! Should I create an issue there rather than here you think?

Config I used for `emacs -Q` as below. Create a new markdown file and ensure `poly-markdown-mode` is active.

<details>
<summary>Minimum config used with emacs -Q</summary>

```emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(package-refresh-contents)

(use-package corfu
  :ensure t
  :bind (:map corfu-map
         ("C-j" . corfu-next)
         ("C-k" . corfu-previous)
         ("TAB" . corfu-insert)
         ("RET" . nil)
         :map org-mode-map
         ("C-," . nil))
  :custom
  (corfu-cycle t)
  (corfu-auto t)
  (corfu-on-exact-match nil)
  :config
  (global-corfu-mode)
  (global-set-key (kbd "M-i") #'completion-at-point))

(use-package tempel
  :ensure t
  :init
  (defun tempel-setup-capf ()
    (setq-local completion-at-point-functions
                (cons #'tempel-complete
                      completion-at-point-functions)))
  (add-hook 'conf-mode-hook 'tempel-setup-capf)
  (add-hook 'prog-mode-hook 'tempel-setup-capf)
  (add-hook 'text-mode-hook 'tempel-setup-capf)
  (add-hook 'eglot-managed-mode-hook 'tempel-setup-capf)
  (setq tempel-trigger-prefix "<")
  (setq tempel-path "~/.config/emacs/templates"))

(use-package markdown-mode
  :ensure t)

(use-package poly-markdown
  :ensure t)
```

**Comment by minad** [comment]
I suspect that the problem is the particular `{python}` template. Insertion of this template will trigger Polymode to perform a switch to a `python-mode` buffer since the block contains Python code, while the rest of the text is Markdown. This may lead to some weird shared state between the original buffer and the Python buffer. Did you also observe problems with other templates, e.g., problems which are purely Markdown or purely Python?

**Comment by fast-90** [comment]
Yes I have tried both, the problem does not exist with pure Markdown or pure Python buffers/templates.

**Comment by fast-90** [comment]
Thanks for the suggestion! Your reply helped me to come up with the following template which works for me:

```emacs-lisp
(py "```{python}" n q n "```")
```

I don't have the undo issue with this one. Maybe the issue was caused by the field created by the `p` in the template in combination with the different buffers created by `poly-markdown-mode`. 

For now I am happy with this solution, so thanks! If I find any future use cases where I do need such a template with polymode I will try to raise the question on their repo as well.
