### ISSUE TITLE
Revise how keys and abbrevs are bound

### ISSUE THREAD

**Issue by minad** [minad/tempel#11]
Currently we have tempel-key and tempel-abbrev. This is related to the possibility of defining templates via macros #3 #10.

**Comment by Luis-Henriquez-Perez** [comment]
Could you describe your idea/vision behind `tempel-key` and `tempel-abbrev`? As in, how do you envision a user (or even yourself) using them to make your workflow productive? I'm genuinely curious. Right now it's vague in my mind and I think perhaps I could be more helpful if I understood this.

**Comment by minad** [comment]
I don't have an idea yet. Maybe we should allow the user to define keys in the template files directly. This helpers have no other purpose than helping the user to define individual keys for highly important templates. For all the other common cases it is better to use tempel-expand or tempel-insert.

**Comment by tpeacock19** [comment]
> We already have too many possibilities how we can hook Tempel into
> Emacs: Individual template keybindings, via abbrev, binding
> tempel-expand to a key, binding tempel-insert to a key, installing
> temple-expand as completion-at-point-function.


Expanding on that comment I do think it is good to have these areas covered.

- Intentional template selection (tempel-insert vs tempel-expand as capf)
  - `tempel-insert`: minibuffer completion, robust in completion-styles.
    Shows all options by default.
  - `tempel-expand` (capf): in-buffer completion, completion-styles
    dependent on company/corfu config. Only shows all options if str is
    empty.
- String completion to template (tempel-expand OR tempel-maybe-expand)
  - `tempel-expand`: completes current string if a full candidate,
    otherwise show all available candidates with str as prefix. Will show
    ALL templates if str is empty.
  - `tempel-maybe-expand`: only completes if current string is a full
    candidate, otherwise passes onto underlying function (ex:
    `indent-for-tab-command` or `completion-at-point`).
- Specific template execution (individual template keybindings)
  - individual keybindings: obviously useful if a user have specific
    templates they wish to refer to often within a specific mode.


These are the three main areas for me, but would be happy to hear if you
all have any others.

The crux of my PR in #13, and area #2 above, is based on an assumption
of using a large library of templates. I experienced this with yasnippet
as well as in the process of converting templates to Tempel. For
example, there are over 100 snippets in the emacs-lisp-mode library for
yasnippet-snippets. Granted, many of them are trivial and in my opinion
will not survive the convertion to Tempel, but I do believe it should be
considered.

**Comment by Luis-Henriquez-Perez** [comment]
>  This helpers have no other purpose than helping the user to define individual keys for highly important templates.

I'm not so convinced that we should delve deep into the area of helping the user bind keys to snippets. Already `template-define-key` seems superfluous to me considering that creating a binding function using `template-insert` is so trivial. As I see it, this package's primary purpose is to provide a framework for defining and inserting snippets. What the users want to do with the templates they define or the functions the framework provides--whether it be binding them to keys or something else--should be up to them.

The only exception I would make to this is if something was so frequently requested and important to the community, especially if it is non-trivial to implement alone, then I it is O.K. to be more flexible and do it even if it goes somewhat out of scope. But binding keys to templates is very trivial to implement and is (as far as I know) not heavily requested.

> Maybe we should allow the user to define keys in the template files directly.

This particularly seems out of scope. Binding keys to snippets is a separate matter from the snippets themselves. The template file should be strictly for defining snippets; it should not additionally bind keys. There are already several ways to do that.

**Comment by Luis-Henriquez-Perez** [comment]
Just in case I want to be clear that when I speak I voice an argument--which is my opinion. I am not intention to berate or "attack" other's idea. I don't mean to sound harsh or judgemental. I am simply objectively and honestly critiquing without sugar-coating anything--in my opinion doing this produces the richest interactions.

**Comment by minad** [comment]
@tpeacock19 I agree with you. I'd like to take a different approach in #13 though.

@Luis-Henriquez-Perez I also agree with you that the wrappers are not necessary. A user could as well write:

~~~ elisp
(define-key map (kbd "C-c t f") (lambda () (interactive) (tempel-insert 'fun)))
~~~

We could however also polish `tempel-key` a bit more such that it can bind multiple keys.

~~~ elisp
(tempel-key map
  "key" template
  "key" template
  "key" template)
~~~ 

Or we just kick it out altogether since as you say, Tempel is not really in the business of keybindings. There is bind-key, general or people use their custom keybinding macros (I do that for example). On the other hand having the helper around does not hurt much and may serve as a starting point?

Regarding `tempel-abbrev` - this one is also utterly unnecessary. However maybe it makes sense to create a function `tempel-abbrev-table` which takes `(tempel--templates)` and turns it into an abbrev table, which can then be registered somehow with the current mode? Not sure how this is done though. The advantage of that is that the user can then use the existing abbrev mechanism and the abbrev keybinding (`C-x '`) to access Tempel, which is nice. I'd like Tempel to plug-in well into the existing infrastructure.

**Comment by minad** [comment]
I improved tempel-key: https://github.com/minad/tempel/commit/b45dcc25ac6f54c6662faec192c711a12c03ac29. I am happy with this form. It is not really needed but still a convenient helper.
