### ISSUE TITLE
`abox` sample template expansion

### ISSUE THREAD

**Issue by c-alpha** [minad/tempel#110]
When I use the `abox` template from the `README.org`, I see an unexpected expansion behaviour. When expansion starts, everything looks as expected:
```
+--+
|  |
+--+
```
The cursor is blinking inside the box. So far so good. Now I type `test` and would expect the box to be expanded, surrounding the word `test`. This is what the actual result is, however:
```
+-----+test
|  |
+-----+
```
As soon as I hit the first key, the cursor jumps to the end of the box's top line, and text gets inserted there.

I have experimented a bit and found that it is the vertical bar (`|` aka pipe character) at the beginning of the second line which triggers this behaviour. If I modify the template to put any character other than a `|` at the beginning of the second line, the template works as expected.

**Comment by minad** [comment]
Hi! Thanks for the report. Unfortunately I cannot reproduce this in my setup. Can you please provide a precise recipe starting from emacs -Q  (including Emacs and package versions)? I assume that some other mode is interfering in your configuration, which handles the pipe character specially.

**Comment by c-alpha** [comment]
> [...]
> I assume that some minor or major mode is interfering in your configuration, which handles the pipe character specially.

You nailed it (once again). It was [Orgtbl Minor Mode](https://orgmode.org/manual/Orgtbl-Mode.html) which interfered. Many thanks!
