### ISSUE TITLE
tempel-eval function

### ISSUE THREAD

**Issue by ispringle** [minad/tempel#114]
Hello, thanks for this great project. I'm wondering how to go about writing a `tempel-eval`/`eval-tempel` function. The idea here is a function that can evaluate the region highlighted, similar to `eval-region` but the evaluated region is consumed by tempel as a new snippet, or overwriting the previously defined snippet.

I'd be happy to do the work to get this implemented, but I was hoping for some guidance here. My lisp skills are pretty subpar and while I've read `tempel.el` I'm a bit confused how to get about this. I know it's possible since there is an auto reload function to reload the tempel files on save.

**Comment by minad** [comment]
Something like this?

~~~~elisp
(defun tempel-eval ()
  (interactive)
  (let ((template (read (buffer-substring-no-properties
                         (region-beginning) (region-end)))))
    (delete-region (region-beginning) (region-end))
    (tempel-insert template)))
~~~

**Comment by ispringle** [comment]
Thanks for the help, I'll get a look at this tomorrow at work. Really appreciate it.
