### ISSUE TITLE
Issue Installing via use-package

### ISSUE THREAD

**Issue by kborling** [minad/tempel#12]
I've tried installing tempel via use-package, and I'm getting the following error in Emacs 28.1:
```
Error (use-package): Failed to install tempel: Package ‘tempel-’ is unavailable 
```

The code I'm using:
```
(use-package tempel
  :bind (("M-+" . tempel-expand)
         ("M-*" . tempel-insert)))
```

It looks like the [Melpa](https://stable.melpa.org/#/tempel) and [Melpa Stable](https://stable.melpa.org/#/tempel) shows package not found.

**Comment by minad** [comment]
Yes it is not yet available.
