### ISSUE TITLE
docs suggestion: examples of longform whitespace preservation in literal strings

### ISSUE THREAD

**Issue by montchr** [minad/tempel#121]
Hello, and thanks for Tempel. I was pleasantly surprised to find that the usage of literal strings in a template defintion can closely approximate the structure of a many-line template. WYSIWYG, almost. It could be helpful to others to see at least one example demonstrating the simple fact that whitespace in strings will preserved verbatim in output. Or, it is also possible that I am overlooking some huge drawback to relying on this behavior.

## Background as user

I was discouraged by what I perceived to be a hard limitation on the syntax accepted by Tempel: none of the examples span more than a couple lines. Which makes sense because that wouldn't be the best way to demonstrate the variety of usages in the space-limited format of a readme. But a longform "file"-length template can be one potential usage that is not demonstrated so obviously.

After realizing the whitespace would be preserved, I felt more encouraged to create more templates with Tempel because it is easier to visualize the result rather than relying on the shorter but abstract syntax for newlines/indentation/etc. (which of course still has its place for most use cases).

## Example

I don't think this would be an ideal example to use directly in the readme, but it was what I wanted to create at the time to fill a need (reduce boilerplate without installing YASnippet or making some unreadable mess with auto-insert skeletons).

Purpose: define a very simple boilerplate file for a NixOS module configuring a program. Not intended to be comprehensive, but just enough to get started.

[Edit: I also just realized that my "module" would not actually work so to NixOS users, please ignore the obvious mistake (perhaps I'll fix in an edit later).]

```el
;;; nix-program-module.nix.eld

nix-mode

(modprog "\
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.programs." (p "pname" pname) ";
in {
  options.programs." (s pname) " = {
    enable = lib.mkEnableOption \"" (s pname) "\";

    package = lib.mkPackageOption pkgs \"" (s pname) "\" {};
  };

  config.programs." (s pname) " = lib.mkIf cfg.enable {
    home.packages = lib.singleton cfg.package;
    " q "
  };
}
")
```

Using "emacs" as the value of the `pname` field, here is the result:

```nix
# modules/programs/emacs.nix
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.programs.emacs;
in {
  options.programs.emacs = {
    enable = lib.mkEnableOption "emacs";

    package = lib.mkPackageOption pkgs "emacs" {};
  };

  config.programs.emacs = lib.mkIf cfg.enable {
    home.packages = lib.singleton cfg.package;
    
  };
}
```

For the time being, in my case, I still need to expand the snippet manually, but ideally it could be invoked more directly upon file creation via some hook or advice.

**Comment by minad** [comment]
Hi, thanks for the report. I don't want to add large examples to the readme. I've added a short paragraph instead. Note that for full file snippets I recommend to use auto insertion instead.
