### ISSUE TITLE
Default template data file location?

### ISSUE THREAD

**Issue by whargrove** [minad/tempel#154]
https://github.com/minad/tempel/blob/34191e9d5fbd5eacdb529b668656ce3a796e85e5/README.org?plain=1#L112

When I inspect the `tempel-path` variable it is in `~/.emacs.d/templates`.

Is the dir dependent on some other Emacs configuration?

**Comment by whargrove** [comment]
The commentary in source code indicates what I observed:
```
;; is compatible with the template format of the Emacs Tempo library.  Your
;; templates are stored in the `tempel-path' (by default the file
;; "templates" in the `user-emacs-directory').  Bind the commands
```

**Comment by minad** [comment]
Let's continue the discussion in #155.
