### ISSUE TITLE
adding a `completing-read` user element: C

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [minad/tempel#16]
As I was starting to integrate `tempel` to my config and write snippets for it, I realized that right now--correct me if I'm wrong--there doesn't seem to an element specify a list of candidates in the minibuffer. The closest element I could see is `p` which allows you to type the input in the minibuffer.

```
(p PROMPT <NAME> <NONINS>) Insert an optionally named field with a prompt.
 The PROMPT is displayed directly in the buffer as default value. 
If NOINSERT is non-nil, no field is inserted.
 Then the minibuffer is used for prompting and the value is bound to NAME.
```

When I had used `tempo` previously I had created a user element `C` for allowing me to specify a list of candidates. This would be the "signature" of the element as I had defined it

```
(C <NAME> PROMPT &rest <COMPLETING-READ-ARGS>)
```

And this is it in action with a custom `helpfn` org link (it opens a `helpful` or--if helpful isn't installed--a `describe` buffer for the specified function). I would get prompted by the minibuffer for the function I wanted. `completing-read` would get called with `obarray` as the collection and `functionp` as the predicate.

```emacs-lisp
 (defsnippet! helpfn ("hfn" org-mode)
  "[[helpfn:" (C fn "function: " ,obarray functionp) "][" (s fn) "]]")
```

In this package, it would be more appropriate to switch the prompt and the name; as that would be more inline with the other elements.

```
(C PROMPT <NAME> &rest <COMPLETING-READ-ARGS>)
```

I think choosing candidates is important enough to warrant its own user element.

**Comment by minad** [comment]
There is `(p (completing-read...)...)`. I am not sure if we should add more custom extensions. See the current syntax extensions here: https://github.com/minad/tempel/#template-syntax. Let's move this discussion to #7.
