### ISSUE TITLE
Retaining 100% Tempo compatibility

### ISSUE THREAD

**Issue by minad** [minad/tempel#18]
The package has been added to GNU ELPA. Try to achieve full compatibility with Tempo.

* Take care to not add too many extensions on top of Tempo.
* Check that all Tempo elements are supported.
* Check that we support the API, at least regarding the functionality. We don't need a precise clone of the API.
* Add support for Tempo configuration options where it makes sense. Maybe support a backward-compatibility mode where Tempel relies on the minibuffer only instead of the in-buffer completion.

**Comment by monnier** [comment]
You could try and take the `tempo-tests.el` that come with Emacs (and throw out the parts that test things for which we don't want to preserve compatibility).

**Comment by minad** [comment]
> You could try and take the tempo-tests.el that come with Emacs (and throw out the parts that test things for which we don't want to preserve compatibility).

That's a good point. The test suite should be ported here. It wasn't added that long ago to Emacs, in May 2019.
