### ISSUE TITLE
overlay persists if snippet is not disposed of properly

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [minad/tempel#19]
If I delete an inserted snippet before exiting naturally with `tempel-next` I'll I end up with two cursors. And the overlays continue to appear in the buffer.

Steps I do.

1. expand a snippet that has overlays (such as `fun`) from trigger
2. delete the snippet immediately

Every time I do this I'll end up with an additional cursor.

I plan to make a gif of this in the near future so it's more clear; but I wanted to make sure I started this issue.

**Comment by minad** [comment]
Yes, the overlays stay around. This is a feature. Don't try to delete them. Instead press ESC or move beyond the last overlay with tempel-next.

**Comment by Luis-Henriquez-Perez** [comment]
> Then the overlays will be "committed".

Sometimes this doesn't work.

> Yes, the overlays stay around. This is a feature.

I don't know if his is a good idea. It's very easy to accidentally delete the snippets and end up with a very difficult to remove overlay or extra cursors. 

I'll continue to study this.
