### ISSUE TITLE
Using `tempel-complete` with `cape-super-capf`

### ISSUE THREAD

**Issue by ashton314** [minad/tempel#20]
I would really like to use `tempel-complete` with `cape-super-capf`. I like the workflow where I just mash my tab key (or complete if in a mode where tab does something other than complete) and based on the stuff before point (or in the region, whatever) it serves up a bunch of choices. Consider the following config:

``` emacs-lisp
;;; File for debugging Emacs setup

;; Setup package manager
(defvar bootstrap-version)
(setq straight-repository-branch "develop")

(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(use-package corfu
  :config
  (corfu-global-mode)
  (setq tab-always-indent 'complete)
  (setq corfu-max-width 150))

(use-package cape
  ;; Bind dedicated completion commands
  :bind (("M-<tab>" . completion-at-point))
  :hook (((markdown-mode scribble-mode latex-mode text-mode) .
          (lambda ()
            (add-to-list 'completion-at-point-functions
                         (cape-super-capf #'tempel-complete #'cape-dabbrev #'cape-dict)))))
  :init
  ;; I'm on a Mac
  (setq cape-dict-file "/usr/share/dict/words")
  ;; Add `completion-at-point-functions', used by `completion-at-point'.
  (add-to-list 'completion-at-point-functions #'cape-dabbrev)
  (add-to-list 'completion-at-point-functions #'cape-keyword))

(use-package emacs
  :defer t
  :init
  (setq enable-recursive-minibuffers t)
  (setq completion-cycle-threshold 1)
  (setq tab-always-indent 'complete))


(use-package tempel
  :defer t
  :diminish ""
  :straight (tempel :type git :host github :repo "minad/tempel"))
```

With the following inside `~/.emacs.d/templates`:

``` emacs-lisp
;; -*- mode: lisp -*-

text-mode

(fooyo "FOO YO!" n)
(foobar "FOO BAR!" n)
(foozoop "FOO ZOOP YO!" n)
```

If I run this in a text-mode buffer with point after `foo`, I do get a pop up when I hit `M-<TAB>`, but when I select the template I get the following error in the messages buffer: `apply: Wrong number of arguments: #<subr tempel--exit>, 3`. Is there something wrong in my config?

<img width="707" alt="Screen Shot 2022-01-11 at 4 28 01 PM" src="https://user-images.githubusercontent.com/2874507/149024526-57c9f163-a506-48c1-ba28-78c7b18a2c54.png">

Vielen Dank.

**Comment by minad** [comment]
There was a bug. It should work now :)

But I recommend against it. It seems better to me to bind all the expansions to different keys. Or add `tempel-expand` to the capf list, which only triggers if you enter an exactly matching template name.

**Comment by ashton314** [comment]
Yay! It is working. Thanks!

> It seems better to me to bind all the expansions to different keys.

I definitely agree with you with the filename expansion. I really like how company worked with this (just smash tab!) but binding filename expansion to its own key has been really comfortable.

I'll try this out a little more; I still think I like the one-capf-to-rule-them-all, but I imagine I'll find cases where I do want the other key.

(Actually, now that I think about it, when I turn on lsp mode, a separate key is probably a better solution, since the lsp-capf doesn't compose.)

Anyway, thank you Daniel!

**Comment by minad** [comment]
> (Actually, now that I think about it, when I turn on lsp mode, a
> separate key is probably a better solution, since the lsp-capf doesn't
> compose.)

As document in the Tempel README, if you add tempel-expand in front of
the lsp-capf you can still use both together. But tempel-expand will
only trigger on exact matches, which can still be convenient if you
remember the snippet/template name.

Btw, what do you think about a snippet collection? The standard
yasnippet collection has too many trivial snippets for my taste, like pt
-> (point). I think these are already served well enough by the usual
Capf completion. What do you use templates for?

**Comment by ashton314** [comment]
> add tempel-expand in front of the lsp-capf

That's probably the route that I will end up taking. (I haven't been deep in my regular workflow for the week; I expect some things will change a bunch!) Thanks!

> Snippet collection

Most of my work is with Elixir and Racket. The templates I use most get me `(λ ($1) $2)$0` in Racket, or `|> IO.inspect($1, label: "$1")$0` in Elixir. (There are a few others that I frequently use, but those are the most-used ones for me.)

I appreciate the examples you've put in the README. I think a good template library is valuable mostly as an *example* of what is possible. :) That said, when I was compelled to use Java, some of the yasnippet libraries were nice. (That's because Java's syntax is :vomiting-face:.)

(Aside: I'm curious to know what you do vocationally; I see some Haskell on your profile. :)

**Comment by minad** [comment]
> Most of my work is with Elixir and Racket. The templates I use most get me (λ ($1) $2)$0 in Racket, or |> IO.inspect($1, label: "$1")$0 in Elixir. (There are a few others that I frequently use, but those are the most-used ones for me.)

The main idea of this package is anyways that you define a bunch of templates you use for a while. You can also quickly comment them out in the templates file if they have fallen out of use.

> I appreciate the examples you've put in the README. I think a good template library is valuable mostly as an example of what is possible. :) That said, when I was compelled to use Java, some of the yasnippet libraries were nice.

I didn't find many Java yasnippets actually. I added one java class example to the Tempel README.

> (Aside: I'm curious to know what you do vocationally; I see some Haskell on your profile. :)

We can discuss via mail :)
