### ISSUE TITLE
Implement post expansion operations

### ISSUE THREAD

**Issue by minad** [minad/tempel#22]
For some snippets it is useful to implement post expansion operations, e.g., calling `org-edit-src-code`. The question is if this is really needed since we support embedded elisp. However it is not particularly pretty with the `ignore`.

~~~ elisp
org-mode

(elisp "#+begin_src emacs-lisp\n#+end_src" (ignore (org-edit-src-code)))
~~~

One could also define a custom user element `edit`.

~~~ elisp
org-mode

(elisp "#+begin_src emacs-lisp\n#+end_src" edit)
~~~

**Comment by Luis-Henriquez-Perez** [comment]
>> However it is not particularly pretty with the ignore.

I don't think the ignore is that bad. It's unclear to me whether this requires an additional abstraction.

>> One could also define a custom user element edit.

This seems like a perfectly O.K. solution.

**Comment by minad** [comment]
Unfortunately it doesn't work very well right now. I have to experiment more.

**Comment by tumashu** [comment]
pre expansion is a useful feature too, at the moment,  before insert template elem,
I want to jump to  the end of line in :ID:, I use  the below template, 

The problem is that, when the current point is under the :ID: line, the p will not work.

```
(contact
 (p (eh-org-end-of-id-line) x t) n>
 ":PHONE: " p n>
 ":EMAIL: " p n>
 ":ALIAS: " p n>
 ":NICKNAME: " p n>
 ":IGNORE: " p n>
 ":ICON: " p n>
 ":NOTE: " p n>
 ":ADDRESS: " p n>
 ":BIRTHDAY: " p)

```

**Comment by MagicRB** [comment]
(testing (p "aei") (ignore))

**Comment by minad** [comment]
@MagicRB Yes, pre- and post-expansion operations didn't work yet. This is a valuable feature to have. I added an implementation in https://github.com/minad/tempel/commit/842f095640de7752140be353b4c146e35560fbd5.

**Comment by MagicRB** [comment]
Thanks!  I can now implement "return to position after template end"

**Comment by MagicRB** [comment]
This seems to evaluate the post hook as if it were a pre-hook
```
  (data "data " (p "Type" ndata) " = " (s ndata)  n>
        "{ " (p "field") " :: " (p "Type") n>
        ", " (p "field") " :: " (p "Type") n> (p (progn (setq tempel-retpoint (point)) nil) retpoint t)
        "}" n>
        "deriving (" (p "Show, Eq") ")"
        :post (progn (backtrace) (message "EN?")))
```

**Comment by MagicRB** [comment]
oh right, `tempel--insert` must eventually return to emacs, i thought `post` is after `tempel--end` ot something

**Comment by minad** [comment]
:post is evaluated after expansion. We could also add an :end hook which is evaluated when the template is finished. But what would you need this for?

**Comment by MagicRB** [comment]
I wanna return to a specific point after expansion, like i showed in the snippet

**Comment by MagicRB** [comment]
I managed to implement it by advising `tempel--end`, but a more generic version would be nice, not necessary tho, i have everything i wanted from this package, really nice package btw.

**Comment by minad** [comment]
cc @tecosaur Post operations have been added :)

**Comment by tecosaur** [comment]
Lovely!

**Comment by tumashu** [comment]
does :pre and :post must behind all template elements？
