### ISSUE TITLE
`(p FORM)` does not create default/auto-resetting fields

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [minad/tempel#23]
When you use the `p` symbol with a string as the PROMPT (let's call it "DEFAULT"), you see "DEFAULT" as the default value, and when you jump to the field specified by `p` and enter text the world `DEFAULT` is replaced by the text you entered.

This is not the case for `(p FORM <NAME> <NONINS>)`. Shouldn't it be? If you enter a form instead of a string for `p` you trigger the `(p FORM <NAME> <NONINS>)`. And in that case the resulting string is not "editable"--in other words, what you type does not replace the inserted text.

The following example illustrate this.

```elisp
(defun oo-tempel-template-one nil
  (when (derived-mode-p 'emacs-lisp-mode)
    (list '(one "[[" (p "hello") "]]"))))
(add-to-list 'tempel-template-sources 'oo-tempel-template-one)

(defun oo-tempel-template-other nil
  (when (derived-mode-p 'emacs-lisp-mode)
    (list '(other "[[" (p (concat "hello" "world")) "]]"))))
(add-to-list 'tempel-template-sources 'oo-tempel-template-other)

;; Try `template-insert` with `one` versus `template-insert` with `other`
```

**Comment by minad** [comment]
This is intentional. The text returned by `FORM` is not a default value, but the field content read via other means, for example via `completing-read`. But if you still want to treat the return value as default, you can propertize the returned string with the property `tempel--default`. So far this is private API, but you can use this if in case you really want this feature.

**Comment by Luis-Henriquez-Perez** [comment]
> Note that the field is still editable, it just does not delete the content automatically as soon as you enter new input.

Yes I know. I use the term "editable" to mean "deletes content automatically" because I dot know of a term describe this. I should have specifically clarified this. This I what I mean from now on.

> But if you still want to treat the return value as default, you can propertize the returned string with the property tempel--default. So far this is private API, but you can use this if in case you really want this feature.

In my opinion we should consider adding a way for the user to be able to do this without having to access the private API. This kind of thing does not seem too out of the ordinary. How this should be done, I'd have to think about. I'm pondering about whether it makes sense for `p` create a field that is "editable" in the case of a string, but not for a form that returns a string. Maybe `p` should be for only these "editable" fields and another element should be for non "editable" ones (maybe `p` and `P`?)?

**Comment by minad** [comment]
I am not sure we need this. I assume this is at best a detail but certainly not something ordinary. In order to make such judgement calls we need a snippet collection (#15). Otherwise I would say we should lean to *not adding new elements* and sticking to the Tempo syntax elements (#18). There are many snippet packages around, maybe a converter or a script to scan for interesting non-trivial snippets is the way to go.

* https://github.com/doomemacs/snippets
* https://github.com/tecosaur/emacs-config/tree/master/snippets
* https://github.com/AndreaCrotti/yasnippet-snippets
* https://github.com/nekop/yasnippet-java-mode
* https://github.com/toumorokoshi/go-snippets
* https://github.com/wdhowe/clojure-snippets
* https://github.com/lukehoersten/haskell-snippets
* https://github.com/hisea/elixir-yasnippets
* https://github.com/mrkkrp/common-lisp-snippets

**Comment by minad** [comment]
Let's keep this open.

**Comment by Luis-Henriquez-Perez** [comment]
> I assume this is at best a detail but certainly not something ordinary.

I wouldn't be too sure. I can only speak for myself but for me this issue came up on my first snippet.

> In order to make such judgement calls we need a snippet collection (#15). Otherwise I would say we should lean to not adding new elements and sticking to the Tempo syntax elements (#18).

I agree that we should be conservative before resorting to adding new elements.

> (what you call editable)

I'll switch to what you use--"defaults"--since that seems to be a more appropriate name.

> we should probably use p/P to always create defaults and add a separate element like p/P which never creates default fields.

Exactly. Yes I'm uncertain it makes sense `(p DEFAULT)` to create defaults `(p FORM)` not to. Seems unexpected to me.

**Comment by minad** [comment]
> Exactly. Yes I'm uncertain it makes sense (p DEFAULT) to create defaults (p FORM) not to. Seems unexpected to me.

What do you use it for? The intended use case was that `FORM` can be used for `completing-read` for example. There it wouldn't make sense to create defaults, since the user already entered their desired value.

**Comment by Luis-Henriquez-Perez** [comment]
> What do you use it for?

The same "org id" snippet I had mentioned in #15 which I reproduce below. I had gotten it to work mainly, but I wanted the `,heading` field to be a default field. Most of the time I will just use the heading name for the name of the link; but sometimes I want to name it myself. Problem is that `heading` can only be computed after I look up the org id. I don't know what it will be in advance and therefore cannot provide a raw string for the template. `p` only provides a default value with a raw string. So with the current elements I have no way of making `,heading` a default field.

```elisp
(let* ((form `(-let* ((org-refile-use-outline-path t)
		      ((_ file _ point) (org-refile-get-location "id"))
		      (id (with-current-buffer (get-file-buffer file) (org-id-get point))))
		(list file point id)))
       (heading `(with-current-buffer (get-file-buffer (cl-first vars))
		   (save-excursion (goto-char (cl-second vars)) (org-get-heading))))
       (template `((p ,form vars t) "[[id:" (cl-third vars) "][" ,heading "]]")))
  (push `(lambda () (when (derived-mode-p 'text-mode) '(,(cons 'idlk template))))
	tempel-template-sources))
```

**Comment by minad** [comment]
In #24 I have a simpler example where "default" fields would be useful.

~~~ elisp
c-mode :condition (bolp)

(inc "#include <" (p (concat (file-name-base (or (buffer-file-name) (buffer-name))) ".h")) ">")
(incc "#include \"" (p (concat (file-name-base (or (buffer-file-name) (buffer-name))) ".h")) "\"")
~~~

**Comment by minad** [comment]
Close due to inactivity.

**Comment by Mango0x45** [comment]
For what it’s worth @minad, I have come back to Emacs recently after a ~2 year hiatus and I would love to have this feature.  My usecase is for C header guards:

```c
/* end result after expansion */

#ifndef DEFAULT
#define DEFAULT

/* points ends up here */

#endif /* !DEFAULT */
```

where I want `DEFAULT` to be:

```elisp
(upcase
 (concat
  (if-let ((project (current-project)))
      (concat (project-name project) "_"))
  (file-name-base (or (buffer-file-name)
                      (buffer-name)))))
```

It would be nice if I didn’t need to resort to private APIs to have this (imo) very reasonable behavior.

I also don’t have examples yet, but I can definitely see myself building other snippets in the future taking advantage of treesitter.  On the neovim side I already have a Go snippet to use treesitter to perform the following expansion:

```go
func Foo() (int, error) {
    /* snippet expands into the following
       if statement, using treesitter to fill
       in return values for me */

    if err != nil {
        return 0, err
    }
}
```

In the above expansion I want `0` as a default, but I want to be able to customize it easily by just typing.

**Comment by Mango0x45** [comment]
Also… while this solution where I explicitly set a property _works_, it completely breaks in conjunction with other modes.  Both `company-mode` and `c-mode` so far have thrown errors with snippets making use of `(propertize (…) 'tempel--default t)`, but all works perfectly both when I use `(p STRING …)` and `(p FORM …)` where the latter doesn’t do any propertize schenanigans.
