### ISSUE TITLE
Could it be merged into Emacs `tempo.el`?

### ISSUE THREAD

**Issue by condy0919** [minad/tempel#26]
I'm a long term `tempo.el` user, the biggest drawback is it has no builtin
mechanism to load snippet files which implies the snippets must be written in
Emacs config.

Also there are tons of `"` around in the following snippet.

``` emacs-lisp
(tempo-define-template "cmake-library"
                         '((P "project: " proj 'noinsert)
                           "cmake_minimum_required(VERSION 3.11)" n n
                           "set(CMAKE_POSITION_INDEPENDENT_CODE ON)" n
                           "set(CMAKE_EXPORT_COMPILE_COMMANDS ON)" n n
                           "project(" (s proj) n
                           "  VERSION 0.1.0" n
                           "  LANGUAGES CXX" n
                           "  DESCRIPTION \"\"" n
                           "  HOMEPAGE_URL \"\"" n
                           ")" n n
                           "include(CTest)" n
                           "include(FetchContent)" n n)
                           "lib"
                           "Insert a cmake library"
                           'cmake-tempo-tags)
```

I hope `tempo.el` have a new template syntax.

**Comment by minad** [comment]
I don't plan to add a new syntax, at least not for now. I consider the sexp/lisp syntax a feature. But you have a point of course with the double quotes. For newlines you could avoid them by simply breaking the line, like docstrings. So the situation is not that bad.

In case you want to experiment with a new syntax you could register your own loading mechanism with `tempel-template-sources`.

Regarding merging into Emacs - I don't have such plans yet, but I want to intend to keep the compatibility (#18).

**Comment by minad** [comment]
Since you're a long term tempo user I M interested in feedback. Does Tempel work for you, do you miss something? Any unexpected behavior?

**Comment by condy0919** [comment]
Thanks for your reply.
