### ISSUE TITLE
Would it be possible to implement the yas-maybe-expand functionality from yasnippet?

### ISSUE THREAD

**Issue by Gira-X** [minad/tempel#29]
From https://joaotavora.github.io/yasnippet/snippet-expansion.html#org87a6f68

> `yas-expand` tries to expand a snippet abbrev (also known as snippet key) before point. YASnippet also provides a conditional binding for this command: the variable `yas-maybe-expand` contains a special value which, when bound in a keymap, tells Emacs to call `yas-expand` if and only if there is a snippet abbrev before point. If there is no snippet to expand, Emacs will behave as if `yas-expand` is unbound and so will run whatever command is bound to that key normally. 

`yasnippet` has this very nice feature as explained above and I wondered if this could also be implemented in `tempel` or if this is out of the scope.

**Comment by minad** [comment]
I don't plan to add such a menu-item. See https://github.com/minad/tempel/pull/13 for a discussion. But you can easily replicate the command in your configuration.
