### ISSUE TITLE
Template configuration, file, directory, macro, hooks?

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [minad/tempel#3]
Since like `tempo` provides a function for defining snippets: `tempo-define-template`. I argue that `tempel` should do the same. I'd rather define the snippets myself and place them throughout my configuration in an order of my choosing where I can document them properly rather than than to be tied to a file.

I dabbled with tempo myself because I wanted the power of lisp for defining templates and to move away from the plethora of snippet files I needed to create for yasnippet. And I wrote a macro `defsnippet!` (I show an example of its use below) for easy and declarative snippet definitions.

```elisp
(defsnippet! defun ("dfn" emacs-lisp-mode)
  "Insert a defun form"
  '("(defun " (p "name" name) " " "(" (p "args" it) ")"
    n> "\"" (p "docstring" docstring) "\""
    n> (p "body" body)
    ")" (p "")))
```

Not to say that such a macro should be written for `tempel`--perhaps too opinionated--but at least a function that can define a template like `tempo` as an alternative to storing all of the snippets in a file.

**Comment by minad** [comment]
Yes, Tempel should offer multiple means to configure the snippets.

* A list of tempel directories and the files inside it.
* A list of tempel files.
* Additional configuration via a macro.
* Maybe even some dynamic facilities to provide mode specific or even context specific templates.

**Comment by minad** [comment]
I think we are sufficiently covered as soon as #4 is merged.
