### ISSUE TITLE
Disable "highlight" after deleting a snippet

### ISSUE THREAD

**Issue by e-eight** [minad/tempel#31]
What I mean by highlight is that whenever I trigger a snippet the entry field is highlighted in a different color. The problem is if I delete the snippet the highlight remains, and the highlighted region extends as I type. For the moment I am just using a lot of inline tempel snippets in Org Mode, and this is very distracting when writing text. Is there any way to turn this off?

**Comment by minad** [comment]
The problem is that you don't quit the templates properly. Therefore the highlighted template fields remain. Use either `tempel-done` or `tempel-next` to move beyond the last field. Then template expansion will finish and the highlights disappear.

**Comment by minad** [comment]
Forgot to mention - to delete the currently active snippet you can also use `tempel-abort`. Take a look at `tempel-map`.
