### ISSUE TITLE
"Special" template triggers

### ISSUE THREAD

**Issue by MagicRB** [minad/tempel#35]
I'd like to be able to trigger templates on `=>` and `{-` for example, would come in handy in Haskell is that doable?

**Comment by minad** [comment]
There is something more to it - if you use Corfu with corfu-auto you may have to reduce corfu-auto-prefix to 2. We could also tweak tempel to automatically reduce the trigger prefix length. This could be reasonable bin cases where template names are two or one letters only.

**Comment by MagicRB** [comment]
I use corfu without auto, manual, and yet it doesnt trigger. Id like to keep `=>` aa thats the natural syntax in haskell and changing would just confuse ky muscle memory

**Comment by minad** [comment]
I don't understand. You use Corfu without auto and yet you would like a tempel auto trigger?

You can also try abbrev-mode and hook tempel into the abbrev mechanism. Then it will auto expand on space.

Furthmore see https://github.com/ymarco/auto-activating-snippets.

I don't want to additional trigger modes. There are already plenty as documented in the readme (capf, abbrev, custom command etc). So you could so build your own auto expander in your config based on Tempel.

**Comment by MagicRB** [comment]
Yeah, sorry, im again having trouble explaining myself. Ive `C-c c` bound to whatever the completion function is, i can never remember, `complete-at-point`? Wait, ill get home do some more testing, maybe its just my config. IF it is than sorry for wasting your time. Amazing package btw, as always 👍

**Comment by minad** [comment]
I have bound `tempel-complete` to a separate key and I also have `tempel-expand` added to the `completion-at-point-functions` with high priority, such that I can trigger it with TAB (`completion-at-point`). It should all be documented in the README. Please try to create well-researched issues, clearly describing the issues, since this reduces a bit the load for the package maintainers and we can avoid going back and forth. I have quite a few packages now which gained some popularity so that would help me to reduce the load a bit. Thanks!

**Comment by MagicRB** [comment]
I've done some debugging and 
```
({- "stuff")
(=> "stuff")
(-- "stuff")
```
but only `--` expands using `completion-at-point`, `tempel-expand` doesn't catch it either. I wasn't just imagining this

**Comment by minad** [comment]
Ah, okay. I see the issue now. Tempel uses `(thing-at-point 'symbol)` to fetch the token at point which is used for completion/expansion. In `haskell-mode` the tokens `=>` and `{-` are not symbol. Therefore they cannot be used as template names. I think this restriction is acceptable. As an alternative I could use the text at point surrounded by whitespace or operators.

**Comment by MagicRB** [comment]
Yeah, it works in `org-mode` but only when im not in insert mode and never in `haskell-mode`

**Comment by MagicRB** [comment]
Yep
