### ISSUE TITLE
Is there a way to send the snippet to standard-output?

### ISSUE THREAD

**Issue by jgarte** [minad/tempel#42]
Is there a way to send the snippet to standard-output?

I'd like to call tempel from the command line in order to use it similarly to [the-way](https://github.com/out-of-cheese-error/the-way).

Can you imagine a way that this would be viable?

My other use case is to pipe the snippet starter text from [vis](https://github.com/martanne/vis/wiki/Differences-from-Kakoune) to emacs and back into vis transformed.

**Comment by minad** [comment]
I don't know if your use case can be realized, since Tempel relies on the Emacs buffer for expansion and creates input fields there. The final result can of course be send to stdout. What are the-way and vis? Can you describe your intended use case a bit more precisely?

**Comment by jgarte** [comment]
vis is a modal text editor, like, vim, that can take any arbitrary text, pipe it to any arbitrary process, and then feed it back into the a vis editor buffer.

I can, for example, select text in visual mode and pipe that text into a script written in any language that uppercases all the characters and then send it back into my vis buffer.

What I'd like to do is pipe some arbitrary text to emacs from vis, have emacs process it, and then send it back through the pipe so that vis can consume it.

In other words, I'd like to start writing the snippet in vis, pipe some tempel template starter text to emacs, and have emacs send me back the expanded snippet.

Another approach, if tempel relies on the emacs buffer to function, is to write my snippet in emacs at some stage in the process and then send it to vis.

I currently use the-way with vis by piping in `<` to vis. In vis' command mode I run `:< the-way search` and it will open the-way to let me fuzzy select a snippet and pipe it into vis. I'd like to do something similar with tempel or maybe hacking tempo or skeleton is the right tool for this job instead?

**Comment by jgarte** [comment]
This might be out of scope for this project. If so, just let me know and I'll close this issue or feel free to close it.

**Comment by minad** [comment]
Yes, this is out of scope of Tempel. But I assume that you could reuse Tempel for your purposes via the API offered by Tempel. To get you started, try `tempel-insert` which expands the given template argument in the current buffer. You could then use the buffer content and pass it to your external tools.

~~~ elisp
(tempel-insert '("Hello, " (p "world") "!"))
~~~

Does this help you?

**Comment by minad** [comment]
But may I ask, the workflow you are describing sounds pretty complicated. Is there a reason for this or do you just want to see if it is possible to glue together these tools? Generally I recommend to rather stay within Emacs if possible and leverage the text processing power of Emacs, I even use Eshell as my main shell.
