### ISSUE TITLE
Questions about tempo syntax

### ISSUE THREAD

**Issue by contrapunctus-1** [minad/tempel#45]
Some questions I couldn't find answers to elsewhere. I'd be happy to make PRs incorporating these into the documentation.

1. I'm trying to make a snippet for `defclass` -
```elisp
(dc "(defclass " (s "name") " (" (s "superclasses") ")" n>
    "(" "(" (p "slot" slot)
             " :initarg :" (s slot) n>
             " :accessor " (s slot) ")" "))")
```             
This one inserts just a single slot, whereas a `defclass` may have one or more slot specifiers. How do I make that happen? The README shows an animation for something similar in LaTeX (insertion of one or more `\item` s), but the example snippet for LaTeX does not seem to have that functionality.
 
2. If one uses `(p "name")`, `name` is inserted, but pressing TAB leaves `name` inserted in the buffer. Is there something which inserts the field prompt but removes it if the user just presses TAB?

**Comment by minad** [comment]
1. The items are repeated by latex mode. Note that you could also read a list from the mini buffer and use that in the template.
2. The default name is only removed when typing

Maybe we add extensions to support additional behavior. But for now tempel is supposed to stay simple. From my experience such overengineered templates are hardly worth it.

**Comment by contrapunctus-1** [comment]
I found a solution for the first which is to my liking - I just defined a new template for slots -
```elisp
(dc "(defclass " (p "symbol") " (" (s "superclasses") ")" n>
    "(" (p "s") "))")
(s "(%" (p "slot" slot)
   " :initarg :" (s slot) n>
   " :accessor " (s slot) > ")")
```

Now I can hit `s TAB` for each slot I want to insert, and still have initargs and accessors defined based on the slot names. It's modular and keeps individual templates simple - fairly elegant.

The other one is still a thorn in my side, though...I can either have default text which I must overwrite if I want to omit the field, or I can have no default text, which is hard to read for complex templates...
