### ISSUE TITLE
Load templates for src block's lang mode in `org-mode`

### ISSUE THREAD

**Issue by alexluigit** [minad/tempel#48]
Hi minad, thanks for creating this awesome package.

I'm quite used to edit source blocks in org-mode directly (ie. without invoking `org-edit-src-code`), so being able to expand the templates for (current) source block's lang mode is important for me. AFAIK, yasnippet supports this by default, meaning a template defined for `emacs-lisp-mode` also works in a "+begin_src emacs-lisp..." source block in org-mode.

Can we have this in tempel as well? 
Here's an attempt to achieve this:
```emacs-lisp
;; line 457 in `tempel-path-templates'
(cl-loop for m in modes
         thereis (or (derived-mode-p m)
                     (eq m #'fundamental-mode)
                     ;; also include templates for current source block's lang mode
                     (and (derived-mode-p 'org-mode)
                          (org-in-src-block-p)
                          (eq (org-src-get-lang-mode (nth 0 (org-babel-get-src-block-info))) m))))
```
There must be better implementations than this one, but I guess it's good enough to demonstrate the purpose.
What do you think?

**Comment by minad** [comment]
Thanks for the suggestion. I am happy to add this. I will give it a try later.

**Comment by minad** [comment]
Thanks for the suggestion. I am happy to add this. I will give it a try later.

**Comment by minad** [comment]
I played around with this a bit longer. It seems that we cannot make this to work well since template expansion also relies on getting the indentation right etc (`indent-according-to-mode`). Therefore I reverted these changes for now until we come up with a better approach. I think `org-edit-special` is the way to go anyway, because of indentation, `completion-at-point` and so on. From what I've seen, yasnippet also doesn't support this feature.

**Comment by alexluigit** [comment]
> To be honest I think you should change your workflow. It simply doesn't work like this. Your approach is a hack which doesn't generalize to arbitrary source blocks and literate programming.

Sorry I didn't made it clear, I only apply the capf hack in my Emacs literate org config file (just one file with a lot of elisp code blocks), kinda experimental. As to `org-edit-src-content-indentation`, I want it to be 0 anyway. I agree that this solution doesn't generalize. 

> Okay I investigated this a bit further. It seems that yasnippet relies on org-babel-do-in-edit-buffer and org-babel-do-key-sequence-in-edit-buffer to do the right thing (which of course it cannot for all operations).

Ah, that explains why I can only expand it by pressing TAB.

>  Therefore my assessment of the situation stays unchanged. Don't do this, don't edit directly in source blocks or use polymode which fixes all the issues properly at the root.

I'll consider changing my workflow, maybe get used to `C-c '` or give `polymode` a shot. Thanks for your 
 suggestion and your time on investigating this issue!
