### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by minad** [minad/tempel#5]
Do we need this or does it only add noise? Possible syntax: `(s name "default")`

**Comment by Luis-Henriquez-Perez** [comment]
I'm not sure one way or another yet. I have written tempo snippets but I need to see examples/write more snippets to get a feel of whether this is useful.

**Comment by tpeacock19** [comment]
I believe showing default values can be useful if one is using snippets you're not completely familiar with or just to provide context as to what is being asked. Though, I'm more referring to the example below that in Yasnippet (left) shows the prompt in the place of the field while Tempel (right) has empty placeholders.

```lisp
(defclass "(defclass " (p "name: " name) " (" (p "inherits: " inherits) ")" n> "("
          (p "slot: " slot ) ")" n> "(:documentation \"" (p "doc: " doc)"\"))")
```

![2022-01-07T08:52:41,448466103-07:00](https://user-images.githubusercontent.com/6407145/148569692-39c04029-be50-4928-af20-36b290ef2b7e.png)

**Comment by minad** [comment]
The question is if we add default values too we are deviating far from Tempo. I am not so certain about that yet. Do we want to define our own language entirely?

**Comment by tpeacock19** [comment]
I think we can keep using the tempo language and if a field is named show its name as a default value?

**Comment by minad** [comment]
> I think we can keep using the tempo language and if a field is named show its name as a default value?

Yes we could do that. But it is not very useful since the variable/field name is usually not a reasonable default value.

**Comment by tpeacock19** [comment]
fair, i guess that is less a default value and more a prompt. which is not used by Tempel unless through a minibuffer interaction.

**Comment by Luis-Henriquez-Perez** [comment]
> But it is not very useful since the variable/field name is usually not a reasonable default value.

I can see it being useful sometimes. For example, suppose I was writing a snippet for creating around advice. I'd probably have the default arguments of the advice be `(orig-fn &rest args)` because for most of the advices I write that's what it is.

Even in having a default value for a function docstring as "TODO" is useful. That way when you have more time or figure out what to write for a docstring you can look it up later. But of course if you know immediately what the docstring could be you can just type it in.

> if one is using snippets you're not completely familiar with or just to provide context as to what is being asked

Yes, the context value alone I think justifies default values. And if you have many snippets, I think this context saves you that split second you need to figure out what goes where.

**Comment by minad** [comment]
@tpeacock19 I am really not yet fully decided about the Tempo extensions. If they are a good idea or not. But we could use the Tempo prompts as default values. It is also a change in behavior over Tempo, but the prompts are currently ignored by Tempel so this could make more sense.

**Comment by tpeacock19** [comment]
>  I am really not yet fully decided about the Tempo extensions. If they are a good idea or not. 

Do you mean the extensions at the bottom of the README? I found that to be a bit confusing with the standard Tempo functionality of 

>  - (p PROMPT <NAME> <NOINSERT>): If `tempo-interactive` is non-nil, the
   user is prompted in the minibuffer with PROMPT for a string to be
   inserted.  If the optional parameter NAME is non-nil, the text is
   saved for later insertion with the `s` tag.  If there already is
   something saved under NAME that value is used instead and no
   prompting is made.  If NOINSERT is provided and non-nil, nothing is
   inserted, but text is still saved when a NAME is provided.  For
   clarity, the symbol `noinsert' should be used as argument.
> - (P PROMPT <NAME> <NOINSERT>): Works just like the previous tag, but
   forces `tempo-interactive' to be true.




> Yes, the context value alone I think justifies default values. And if you have many snippets, I think this context saves you that split second you need to figure out what goes where.

This also reminds me of another question I had about the ordering of template entry. Though I'm not certain how often it may be there could be some use in defining which variable/field to jump to with `tempel-next`. Unless I missed this somehow.

**Comment by minad** [comment]
I made two changes:

* Use prompt as default (https://github.com/minad/tempel/commit/91f6978ddd853b9c5ff181010c64a225f4fa84c7)
* Add special treatment for default values (https://github.com/minad/tempel/commit/c8bd4d7e9577db2d8adc2e291e9ce31a597ad1e4)

This way we stay close to the original Tempo language.

**Comment by minad** [comment]
@tpeacock19 Please take a look if it is more clear now. I removed the q extension. We stay very close to the original Tempo language now.

**Comment by tpeacock19** [comment]
Yeah those changes look good. And the docs are more clear.

I see that the capital `(P PROMPT <NAME> <NOINSERT>)` form is just
grouped with Tempel's `(p DEFAULT <NAME> <NONINS>)` which I think is
fine. However, it may conflict with a user expecting to get a
minibuffer prompt rather than an overlay. Do you think this needs to be
considered?

**Comment by minad** [comment]
I implemented something better in https://github.com/minad/tempel/commit/675e759bdead7cc91307e98284af1de2e8c2a58d and https://github.com/minad/tempel/commit/0aa4e8c37fbc96e90ae4eafcc33c7583a056c29c. Please try it. I think the behavior is very much aligned with Tempo now.

**Comment by tpeacock19** [comment]
great! I think this works well.
