### ISSUE TITLE
company-prefix should maybe be omitted

### ISSUE THREAD

**Issue by jdtsmith** [minad/tempel#50]
One issue with hardcoding `:company-prefix t` when using a trigger prefix: if you put `tempel-complete` in as a CAPF, anywhere that trigger key appears, immediate auto-completion will occur.  This will obviously cause issues in programming languages, HTML buffers, etc.  I can see the idea there, but I think just respecting corfu-auto-prefix is a better default setting.  You can always (e.g.) `< M-Tab` if you want to see all your available prefixes.

**Comment by minad** [comment]
1. You can use a different trigger char
2. You can overwrite the setting with Cape

**Comment by minad** [comment]
Btw. I was thinking about doing in the opposite way, adding a cape-trigger-char-capf wrapper.

**Comment by jdtsmith** [comment]
> You can use a different trigger prefix per buffer 

Do you mean use a "rarely enter character"?  

> You can overwrite the setting with Cape

Yes it's easy to disable this setting with Cape or a wrapper which strips :company-prefix out, but for most users, :company-prefix will only have an effect when using auto-completion.  They might be surprised/annoyed that by default every time their trigger char is entered they get a popup.

**Comment by minad** [comment]
> Do you mean use a "rarely enter character"?

Yes, use a rare character. You can even use more than one character.

> Yes it's easy to disable this setting with Cape or a wrapper which strips :company-prefix out, but for most users, :company-prefix will only have an effect when using auto-completion. 

The prefix has only an effect for auto completion.

> They might be surprised/annoyed that by default every time their trigger char is entered they get a popup.

No. It is called trigger prefix, isn't it? Anyway, I am not sure I recommend `tempel-complete` as Capf. I prefer `tempel-expand`.

**Comment by minad** [comment]
There was a bug which made the situation worse. Now if you enter `< SPC` quickly, tempel should not come up. See https://github.com/minad/tempel/commit/a3b35cf2432b4614aeae7c3382a8b1e7bfaf4002. I think this should also resolve your issue and you don't have to resort to using Cape.

**Comment by david-vicente** [comment]
> 1. You can use a different trigger prefix per buffer

Can you share how to accomplish that? I'm interested in a different prefix by mode.
