### ISSUE TITLE
`tempel-path` as directory vs backup files

### ISSUE THREAD

**Issue by jdtsmith** [minad/tempel#51]
I thought it might be nice to make `~/.emacs.d/templates` into a directory, and organize templates in various files there.  The nice thing is I can organize this however I want: by mode, or by some other category I devise, and can have as few or as many templates per file as desired.  I suspect any future Tempel template library will want to do the same.

This works well with a "clean" directory, but `tempel-path-templates` reads _all_ files nested in the directory, including auto-saves (`file~`) and undo-tree compressed files (`.file.~undo-tree~.gz`).  The latter are rather problematic because Tempel attempts to decompress and read them, which results in no templates being read. 

 I can think of a couple of solutions:

1. Have a required file extension for template files inside of directories, like `file.tmpl` or similar, and read only those.
2. Have a list of _exclude_ patterns that include some common ones like `*~` and `*~.gz`, and skip such files.

**Comment by minad** [comment]
Good point. I switched to use wildcards instead.

**Comment by jdtsmith** [comment]
Thanks. I see that this will no longer recurse directory structures looking for matching files.  Some might like `templates/fundamental.tmpl` and `templates/org/org_export.tmpl` together.

**Comment by minad** [comment]
That's okay. You can specify multiple paths.

**Comment by jdtsmith** [comment]
Yes, but then you and all the users have to remember to add those paths every time you widen your directory structure; maybe not ideal for template libraries.  Wildcard file-only matcher + recursion of directories?

**Comment by minad** [comment]
I think it is good enough. You can add your own template loaders if you disagree. I don't think there won't be template libraries soon. If something emerges one can reconsider. But then I think template libraries will probably use a regular directory structure.

**Comment by minad** [comment]
I neither want to add exclude patterns nor do I want to define a file extension. Personally I keep my templates in a single file. Maybe someone will add a special loader which loads the templates from an org file. We will see.

**Comment by minad** [comment]
Btw, one could also just undo this and go back to the recursive loader. I configure my Emacs to not leave backup files, auto save files, lock files, etc., around. I think this is a pretty big misfeature of Emacs and it is one of the first things I disable when starting with an Emacs from scratch.

**Comment by jdtsmith** [comment]
> I neither want to add exclude patterns nor do I want to define a file extension.

I meant leave it to the user to do so.

**Comment by minad** [comment]
How? Then we need additional configuration variables.

**Comment by jdtsmith** [comment]
> How? 

Let `tempel-path` optionally contain (a list of) `(dir . file-wildcard)`?

**Comment by minad** [comment]
What is the meaning of `(dir.file-wildcard)`? But I wonder what is wrong with the current approach? The intended design is that users or libraries with more complex requirements can define their own template loader. For this reason I think it is perfectly fine to go with a simple solution like the one we have now.

**Comment by minad** [comment]
Also note that people may not even like the tempo syntax. It would be as well possible to translate from a yas-like syntax to the tempo representation internally. Some people prefer to define templates in their init.el instead. There is no one fits all solution for the template loading.

**Comment by jdtsmith** [comment]
> What is the meaning of `(dir . file-wildcard)`

E.g. `("~/.emacs.d/templates" . "*.tmpl")` would find and load all `.tmpl` files underneath `~/.emacs.d/templates`.  

Only problem with current approach is it doesn't allow you to reorganize files & dirs arbitrarily in the directory without also reconfiguring `tempel-path` to match.  But it's not such a big problem.  E.g. if you keep the same two-level hierarchy you could set to `~/.emacs.d/templates/*/*.tmpl` and add directories at will. 

Holding tempels in a org structure would also be a great and easy to navigate solution.

**Comment by minad** [comment]
> Holding tempels in a org structure would also be a great and easy to navigate solution.

Yes one could imagine much fancier loaders. A translation of `"foo{{{p}}}bar" -> `("foo" p "bar")` should be possible and would let you write the templates in their target language. One could keep the templates in Org source blocks. This functionality is out of scope for Tempel but maybe someone is interested in creating a separate org-tempel package.
