### ISSUE TITLE
Use 3rd party elisp libraries

### ISSUE THREAD

**Issue by jgarte** [minad/tempel#52]
Hi,

How can I use 3rd party elisp libraries like [uuidgen.el](https://github.com/kanru/uuidgen-el) in my tempel snippets?

I tried the following but it complained of not finding `uuidgen.el`:

```
(uid (uuidgen nil))
```

**Comment by minad** [comment]
No idea. You probably didn't install uuidgen.el properly. The function is autoloaded so this should just work.

**Comment by jgarte** [comment]
hmmm, I installed it with Guix and it does work in a regular elisp buffer but not from the tempel file.

Vanilla emacs lisp libraries work though.
