### ISSUE TITLE
Sourcing multiple template files

### ISSUE THREAD

**Issue by jgarte** [minad/tempel#54]
Hi, Is there a way to source multiple template files in addition to `templates`?

Is there a way to compose tempel templates directly in my `init.el` as elisp code?

**Comment by minad** [comment]
Did you look at the documentation and the configuration options?

https://github.com/minad/tempel#adding-template-sources

https://github.com/minad/tempel/blob/b88c58a89390cf3834de898109c5e69a5cf434cd/tempel.el#L51-L54

https://github.com/minad/tempel/blob/b88c58a89390cf3834de898109c5e69a5cf434cd/tempel.el#L81-L86

**Comment by jgarte** [comment]
Sorry, those examples weren't clear/explicit to me on how to add multiple template files as a newer emacs user.

**Comment by jgarte** [comment]
@minad 

I tried this
```
(require 'tempel) (setq tempel-path "~/snippets") 
```

But emacs is still looking for `~/.emacs.d/templates`.

What newbie mistake am I committing?

**Comment by jgarte** [comment]
Oh, the reason this didn't work is because `tempel-path` doesn't exist in the version I'm using. It's called `tempel-file` in version 0.3 :()

**Comment by minad** [comment]
I released a new version. It was about time.

**Comment by jgarte** [comment]
> I released a new version. It was about time.

Thanks! I sent a patch to GNU Guix for the new version `0.4`: https://issues.guix.gnu.org/56470
