### ISSUE TITLE
Dynamic/"On the Fly" Templetes 

### ISSUE THREAD

**Issue by fejfighter** [minad/tempel#56]
My only use-case for snippet libraries has traditionally been for dynamically generated function argument templates when completing with CAPF, particularly with eglot.

I think this could be supported in tempel by splitting the lookup and expansion logic into separate functions and exposing a `(temple-expand-this "<snippet>")` function for use in this case.

**Comment by minad** [comment]
See tempel-insert. The function expects a template name or template sexp in Tempo syntax.

**Comment by fejfighter** [comment]
Sorry for the noise, did not realise tempel-insert could do both
