### ISSUE TITLE
Consideration of an additional string based syntax?

### ISSUE THREAD

**Issue by Inc0n** [minad/tempel#59]
The current lisp based template is great, however, it does suffer from the readability. 
What I mean by string based syntax, is just using `$` to embed the tempel syntax, so that everything can be put into one single string.
This way a parsing function will be used to transform this string based syntax back into the lisp based tempel template.

For example, `(tempel-parse-template "proc $p($p): $(p 'return-type) =\n")` will produce `("proc " p "(" p "): " (p 'return-type) " =\n")`.

The parsing logic here is fairly straight forwad, it will split string at where `$` and where the tempel syntax charaters will follow.

The more difficult part which I haven't thought of is how to integrate this with `tempel-path` tempel template definition files.

What is your thought on this?

<details><summary>Implemetation</summary>

```
(defun tempel-parse-template (string)
    (cl-labels
	((aux (string acc)
	      (if (string-empty-p string)
		  (nreverse acc)
		(if-let* ((index (cl-position ?$ string)))
		    (cond ((= (aref string (1+ index)) ?\()
			   (pcase-let ((`(,obj . ,idx)
					(read-from-string string (1+ index))))
			     (message "%s %s" obj idx)
			     (aux (cl-subseq string idx)
				  (-cons* obj
					  (cl-subseq string 0 index)
					  acc))))
			  ((string-match "[rn]>\\|[prn>&%oq]"
					 string (1+ index))
			   (pcase-let ((`(,start ,end)
					(match-data 0)))
			     (aux (cl-subseq string end)
				  (if (= index 0)
				      (cons (intern
					     (cl-subseq string start end))
					    acc)
				    (-cons* (intern
					     (cl-subseq string start end))
					    (cl-subseq string 0 index)
					    acc)))))
			  (:else
			   (user-error "Invalid $ exp at %s %d %s"
				       string index
				       (cl-subseq string index))))
		  (nreverse (cons string acc))))))
      (aux string '())))
````
</details>

**Comment by minad** [comment]
A separate syntax is out of scope for now, but we can consider it for the future.
