### ISSUE TITLE
tempel-complete may cause `clangd' to emit error msg "trying to get preamble for non-added document"

### ISSUE THREAD

**Issue by smallzhan** [minad/tempel#60]
tested `emacs -Q` with minimal configuration.

``` emacs-lisp
(add-to-list 'load-path "~/.emacs.d/straight/repos/eglot")
(add-to-list 'load-path "~/.emacs.d/straight/build-28.1.50/tempel")

(require 'eglot)
(require 'tempel)

(add-hook 'c-mode-hook 'eglot-ensure)
```
the tempel snippet 
```
(ifndef "#ifndef " (p "ifndef-clause: " clause) > n "#define " (s clause) n> p n "#endif /* " (s clause)" */" n>)
```
then open a file named `test.c`, and then eglot connect the server clangd. 

type `ifndef<tempel-complete>` fill the snippet with something, and using tempel-next to exit the snippet. now everything is ok.

but when I delete even a single character that is expanded with the snippet, the `clangd' server hangs, with the error "trying to get preamble for non-added document".  
![Jul-07-2022 00-14-48](https://user-images.githubusercontent.com/1635790/177596669-0d1bda35-a72f-4663-96ee-f8eca831411e.gif)

**Comment by minad** [comment]
This sounds more like an Eglot issue than a Temple issue. Could you investigate the reasons for the hanging a bit deeper?

**Comment by smallzhan** [comment]
tried "lsp-bridge + tempel"(ERR),  "eglot+yasnippet"(OK), "lsp-bridge+yasnippet"(OK).
by the way,  tempel with `tree-sitter-hl-mode'([emacs-tree-sitter](https://emacs-tree-sitter.github.io/getting-started/)) may mess  c-mode syntax highlight.

**Comment by smallzhan** [comment]
After some testing, I've found that the problem is as follows:

LSP rely on the "didChange" request, which is called in `after-change-functions' hook. But when tempel expand the snippets which contains `(s clause)',  ONLY the first filed which is typed by user triggered the "didChange", the `(s clause)' field changed but there is no "didChange" request,  so after the expansion, the status is inconsistent between local and server side.  Then clangd hangs.

Have any suggestions ?

**Comment by minad** [comment]
Is this a duplicate of #34? I thought this was fixed a while ago?

**Comment by mssdvd** [comment]
I think the bug only occurs with snippets containing placeholders.
