### ISSUE TITLE
Changing Template: to Snippet: 

### ISSUE THREAD

**Issue by jgarte** [minad/tempel#61]
Hi,

What would be a good approach for changing `Template: ` to `Snippet: ` in my personal config?

Should I be using `advice-add`? https://www.emacswiki.org/emacs/AdvisingFunctions

https://github.com/minad/tempel/blob/main/tempel.el#L681

**Comment by minad** [comment]
Maybe an advice. You could also create your own patched version of you are unhappy with such minor details. I don't see the point.

**Comment by jgarte** [comment]
Just brainstorming on how to do this and a roundabout way to learn ways to hack emacs

**Comment by minad** [comment]
I understand. But to be clear, I don't really appreciate such basic general questions on my issue trackers. This is an issue tracker after all. Please note that I maintain a bunch of relatively popular packages and it costs time to dig through the real issues. Furthermore if this is a serious question, I think you should reconsider your way of configuring Emacs - this seems like some case of Emacs configuritis if you want to change minor details like this. I recommend that you avoid unnecessary detours and focus on the essentials. Keep your configuration simple! I hope you don't mind me being direct. Thanks!
