### ISSUE TITLE
Please provide some examples for template files

### ISSUE THREAD

**Issue by Crandel** [minad/tempel#63]
In README.md you mentioned:

```
The templates are defined in a Lisp data file configured by tempel-path
```

I have no idea about Lisp data files. Should it be `<mode>-template.el` file?

I'm trying to migrate from yasnippet with this structure

```
$EMACS_CONFIG_DIR/snippets/
                 |__go-mode/
                    |_a
                    |_b
                    ...
                 |__python-mode\
                    |_a
                    |_b
                 ...
```

And create similar structure

```
$EMACS_CONFIG_DIR/template/
                 |__go-mode-template.el
                 |__python-mode-template.el

```

So as the first try I create file `$EMACS_CONFIG_DIR/template/fundamental-template.el`

```
fundamental-mode ;; Available everywhere

(today (format-time-string "%Y-%m-%d"))
```

But when I'm trying to run tempel-expand I get
```
tempel-expand: No completions
```

**Comment by minad** [comment]
Please read the manual/README.

**Comment by minad** [comment]
I clarified the section about Lisp data files. Note that you could have also gotten this answer by entering `C-h f lisp data RET`. I strongly suggest to use the Emacs self documentation features. In case of doubt, dig into the code.

**Comment by Crandel** [comment]
This is my config

```
(use-package tempel
  :ensure t
  :commands (tempel-expand)
  :bind (("M-+" . tempel-complete) ;; Alternative tempel-expand
         ("M-*" . tempel-insert))
  :init
  (setq tempel-path (expand-file-name "templates/*" user-emacs-directory))
  ;; Setup completion at point
  (defun tempel-setup-capf ()
    ;; Add the Tempel Capf to `completion-at-point-functions'.
    ;; `tempel-expand' only triggers on exact matches. Alternatively use
    ;; `tempel-complete' if you want to see all matches, but then you
    ;; should also configure `tempel-trigger-prefix', such that Tempel
    ;; does not trigger too often when you don't expect it. NOTE: We add
    ;; `tempel-expand' *before* the main programming mode Capf, such
    ;; that it will be tried first.
    (setq-local completion-at-point-functions
                (cons #'tempel-expand
                      completion-at-point-functions)))

  (add-hook 'fundamental-mode-hook 'tempel-setup-capf)
  (add-hook 'prog-mode-hook 'tempel-setup-capf)
  (add-hook 'text-mode-hook 'tempel-setup-capf)
)

(provide 'tempel-rcp)
```

I create a file `/home/crandel/.config/emacs/templates/fundamental-mode`

```
fundamental-mode ;; Available everywhere

(today (format-time-string "%Y-%m-%d"))
```

But still get the error when I write `today` and call `tempel-expand` in fundamental-mode

```
let: End of file during parsing
```

`tempel-path`

```

tempel-path is a variable defined in tempel.el.

Value
"/home/crandel/.config/emacs/templates/*"
```

**Comment by minad** [comment]
> |let: End of file during parsing |

Can you obtain a stack trace for this error? I don't see where this
error is coming from but it must be a configuration problem since Tempel
works well for me. Such an error could occur for example if your
template file contains syntax errors.

**Comment by Crandel** [comment]
Yes, I miss last bracket in `fundamental.eld`

Sorry for bothering you and thank you for amazing work
