### ISSUE TITLE
Can a FORM return elements of a snippet?

### ISSUE THREAD

**Issue by nicolas-graves** [minad/tempel#65]
Hi! 

I am struggling for a template which should behave differently given a prompted value, was wondering how a `FORM` can itself evaluate to complete the list of elements of the snippet. 

I've tried many different things, to no avail. Is this possible somehow ? 

Just a small example with an incorrect but understandable syntax:
~~~ emacs-lisp
(uri
                      "(uri " (,@(cl-case (intern "url-fetch")
                                         ('git-fetch '("git-reference..."))
                                         ('svn-fetch '("svn-reference..."))
                                         ('hg-fetch  '("hg-reference..."))
                                         ('cvs-fetch '("cvs-reference..."))
                                         ('bzr-fetch '("bzr-reference..."))
                                         (t          '("(string-append \"https://" p ".tar.gz\")"))))
                      ")")
~~~

EDIT: formatting source block

**Comment by minad** [comment]
Such recursive templates are not supported.
