### ISSUE TITLE
[Question] Syntax element like `r` but that doesn't quit

### ISSUE THREAD

**Issue by david-vicente** [minad/tempel#66]
Is there a way to get something like what the title suggests?

As a use case consider this template:

```emacs-lisp
python-mode

(ifei "if " p ":" n> r> n "elif " p ":" n> q n)
```
This works when I have some selected region, as I can continue filling the remaining fields. However if I call the same template without a selected region, it quits when I get to `r>`.

A workaround would be having two separate templates:

```emacs-lisp
python-mode

(ifrei "if " p ":" n> r> n "elif " p ":" n> q n)
(ifei "if " p ":" n> p n "elif " p ":" n> q n)
```
but it isn't ideal.

**Comment by minad** [comment]
Oh this sounds like a bug. @fritzgrabo Didn't we implement quitting only for r fields occuring at the end?

**Comment by minad** [comment]
@fritzgrabo nevermind. @david-vicente See https://github.com/minad/tempel/pull/44#issuecomment-1115324006
