### ISSUE TITLE
Template collection: tempel-collection

### ISSUE THREAD

**Issue by Crandel** [minad/tempel#68]
Hi @minad,
Thank you very much for this great project.
I prepare small project - [tempel-collection](https://github.com/Crandel/tempel-collection), inspired by [yasnippet-snippets](https://github.com/AndreaCrotti/yasnippet-snippets) project. 

I welcome everybody to use it or contribute.

**Comment by minad** [comment]
Very good, thanks for letting me know!

**Comment by Arian-D** [comment]
Hey @minad,
Would you be able to mention this project on the README?

**Comment by minad** [comment]
@Arian-D Sure, but so far not much has happened. The collection is not yet available as package. See also #78.

**Comment by Crandel** [comment]
@Arian-D Hi Arian,
If you know how to make a package in Melpa fill free to make a pull request in tempel-collection repository.

**Comment by mpenet** [comment]
@minad I personally think these things are better kept separate. I never liked the mega pack of yasnippets (I pushed back against the clojure ones being merged on yasnippets snippets collectoin, even tho they ended-up doing this, respecting the license), regardless of them being opinionated or not. It's nicer to be able to pick & choose imho.

**Comment by mpenet** [comment]
On a somewhat related note, feel free to critique/re-use the code I did to make it melpa ready and easily consumable. It's quite straightforward.

**Comment by minad** [comment]
On 11/22/22 10:12, Max Penet wrote:
> @minad <https://github.com/minad> I personally think these things are
> better kept separate. I never liked the mega pack of yasnippets (I
> pushed back against the clojure ones being merged on yasnippets snippets
> collectoin, even tho they ended-up doing this, respecting the license),
> regardless of them being opinionated or not. It's nicer to be able to
> pick & choose imho.

I don't really care, since I maintain my own private snippets anyway.
However the situation is obviously not great if we end up with a
tempel-collection and separate tempel-clojure, tempel-foo packages etc.
Maybe tempel-collection should be split up then.

**Comment by mpenet** [comment]
> Maybe tempel-collection should be split up then.

I think so too. 

Ultimately, if packaged properly (**adding** to the extra template-path and not setting/replacing it), it doesn't really matter, you can have as many template sources as you want. Then it's just really a matter of naming.

**Comment by minad** [comment]
On 11/22/22 10:24, Max Penet wrote:
>     Maybe tempel-collection should be split up then.
> 
> I think so too.

You think so, but not sure if everybody agrees.

> Ultimately, if packaged properly (*adding* to the extra template-path
> and not setting/replacing it), it doesn't really matter, you can have as
> many template sources as you want. Then it's just really a matter of naming.

One problem is that you have to duplicate all the code to setup the
path. I think this is an argument against separate packaging. There is a
lot of unnecessary duplication, testing, ...

**Comment by Crandel** [comment]
Right now it's just a one file per mode in templates directory. @mpenet How exactly do you see the split? Bunch of repos with one file on it?

**Comment by mpenet** [comment]
Yes pretty much. 
If that's to be(come) the "official" tempel repos for `<language x>` I think that makes more sense. Otherwise if it's personal you're free to do as you'd like. 

Making a (melpa or git usable) package is very low effort.

**Comment by Arian-D** [comment]
One solution that I can think of is to add separately maintained template repos as git submodules, which would make it easier for users to choose whether they would like the entire collection or mode-specific templates.

The other way is to wait until some writes a working yasnippet to tempel template converter :sweat_smile:

**Comment by mpenet** [comment]
> One solution that I can think of is to add separately maintained template repos as git submodules, which would make it easier for users to choose whether they would like the entire collection or mode-specific templates.

That makes packaging more complex and imho maintainance a burden (lots to track). 

With single repo per context, for the end-user it's just one line to setup via use-package or just one package-install away, no need to mess with paths, it just works. 
If you wanted to use tempel-clojure you could just do `(use-package tempel-clojure)` and you're done, it adds it to the path for you. It's very low overhead for the end-user.

**Comment by Crandel** [comment]
I see no reason to have tons of different packages with one file on it. Make no sense. It just one file with templates per mode. No harm to have them in one repo. But will be a good example to everyone, who want to improve templates or create the new one for new mode

**Comment by minad** [comment]
I think the situation will be like this - a mega pack will "win" if accepted by the package archives (MELPA/ELPA), since it can always merge in template files from per-language packages, even against push back. @Crandel could make the first step and take @mpenet's Clojure templates. ;) Vice versa, per-language packages won't have a good chance to get added to the package archives, since one could just use the larger collection package instead and add the templates there. Note that this will reduce the work for the package archive maintainers.

Anyway, for me the problem with the package archives is that they contain so much cruft. I wouldn't even know where to start and I think one should have some knowledge of the available templates. The good thing is that the Tempel templates are very concise, as can be seen in @mpenet's or @Crandel's repository. At least for me, this feels much better than the situation with Yasnippet.

I've mentioned before the issue of controversial templates. I think one should avoid adding templates which are not common patterns or which are not expected to be used by 90% of the users. In tempel-clojure I found at least one template, which I think wouldn't pass this threshold: The bench template seems like a bad pattern. But besides that, most users would probably agree with what is there.

**Comment by minad** [comment]
On the other hand it could happen also the other way round. If https://github.com/melpa/melpa/pull/8282 gets accepted into MELPA, the MELPA maintainers may reject a catch all template package and instead suggest that per-language packages are the way to go.

But at least in the case of NonGNU ELPA I am quite sure that the maintainers there won't accept a bunch of tempel-* packages. They would probably accept a single tempel-collection package. They may even suggest that the templates could be provided as part of tempel itself, which I would like to avoid.

**Comment by mpenet** [comment]
Bench is a port of the yas version, I agree about its style but it's actually quite useful for quick/rough profiling without pulling an external library initially like criterium, I know quite a few people who use it on yas. 

I don't think there needs to be a preferred solution, some  will like a mega pack, some don't, both can (and likely) will be available. I have seen megapacks lag in features/fixes behind smaller dedicated packages quite a few times. Rarely the maintainer will be knowledgeable about all languages in the pack and ultimately you can end up with a pack that includes stuff that shouldn't be there or stuff that's missing.

**Comment by mpenet** [comment]
Like I said, some will prefer one solution over the other. I am not saying it wouldn't work.

Personally I like to have my emacs conf as a single file, so I value granularity/composability via use-package  vs having to copy/carry files  with my config. But maybe I am on the extreme side.

About elpa, I am not aiming for that, but I know for melpa it wouldn't be an issue, it's full of yasnippets packages for specific languages already.

**Comment by minad** [comment]
> Personally I like to have my emacs conf as a single file, so I value granularity/composability via use-package vs having to copy/carry files with my config. But maybe I am on the extreme side.

Note that you can define Tempel templates inside your init.el. See https://github.com/minad/tempel/tree/e5f7604a4c3289d4252743fa07c93daeebb1b383#adding-template-sources.

**Comment by mpenet** [comment]
I noticed! It's useful but I think leveraging use-package is really pretty for that: 
https://github.com/mpenet/emax/blob/86a0d3f9ba646738bb78ffdf127b4bd9d12d3e28/init.el#L508

It fetches/install/compiles &  adds it to tempel template path in one go, it requires no work from the consumer. Once on melpa it's going to be just (use-package tempel-clojure) and you're done.

**Comment by Crandel** [comment]
I prepare a [PR](https://github.com/melpa/melpa/pull/8285) to package tempel-collections via Melpa

**Comment by minad** [comment]
I added links to the README.
