### ISSUE TITLE
User defined elements tempo-user-elements, Tempel extensions

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [minad/tempel#7]
This would possibly be in the form of a macro `tempel-defelement`.

**Comment by Luis-Henriquez-Perez** [comment]
For reference I will include the part of the documentation of how `tempo` handles creating custom elements. Not that we have to do it this way, but it's nice to have a precedent.

```text
 - Anything else: Each function in tempo-user-elements is called
   with it [the unrecognized element] as argument until one of them returns non-nil, and the
   result is inserted.  If all of them return nil, it is evaluated and
   the result is treated as an element to be inserted.  One additional
   tag is useful for these cases.  If an expression returns a list (l
   foo bar), the elements after l will be inserted according to the
   usual rules.  This makes it possible to return several elements
   from one expression.
```

**Comment by minad** [comment]
Tempel current allows arbitrary lisp forms. See https://github.com/minad/tempel#template-syntax:

~~~ elisp
(FORM ...) Other Lisp forms are evaluated. Named fields are lexically bound.
~~~

So the question is if we want to keep this. However custom user elements could be tried just before attempting evaluation.

**Comment by minad** [comment]
Addressed in #9. We can continue the discussion there.

**Comment by minad** [comment]
*Comment by @Luis-Henriquez-Perez copied from #17*

------

As I was starting to integrate `tempel` to my config and write snippets for it, I realized that right now--correct me if I'm wrong--there doesn't seem to an element specify a list of candidates in the minibuffer. The closest element I could see is `p` which allows you to type the input in the minibuffer.

```
(p PROMPT <NAME> <NONINS>) Insert an optionally named field with a prompt.
 The PROMPT is displayed directly in the buffer as default value. 
If NOINSERT is non-nil, no field is inserted.
 Then the minibuffer is used for prompting and the value is bound to NAME.
```

When I had used `tempo` previously I had created a user element `C` for allowing me to specify a list of candidates. This would be the "signature" of the element as I had defined it

```
(C <NAME> PROMPT &rest <COMPLETING-READ-ARGS>)
```

And this is it in action with a custom `helpfn` org link (it opens a `helpful` or--if helpful isn't installed--a `describe` buffer for the specified function). I would get prompted by the minibuffer for the function I wanted. `completing-read` would get called with `obarray` as the collection and `functionp` as the predicate.

```emacs-lisp
 (defsnippet! helpfn ("hfn" org-mode)
  "[[helpfn:" (C fn "function: " ,obarray functionp) "][" (s fn) "]]")
```

In this package, it would be more appropriate to switch the prompt and the name; as that would be more inline with the other elements.

```
(C PROMPT <NAME> &rest <COMPLETING-READ-ARGS>)
```

I think choosing candidates is important enough to warrant its own user element.

**Comment by minad** [comment]
@Luis-Henriquez-Perez There is `(p (completing-read...)...)`. See the current syntax extensions here: https://github.com/minad/tempel/#template-syntax. I am not sure if we should add more custom extensions, since `FORM` and `(p FORM)` already cover most use cases like the `completing-read`use case. The only "downside" is that you have to write plain Lisp functions. 

However we lack the possibility to define custom elements. In particular we lack the ability to generate elements dynamically. One could imagine for example a custom syntax extension which expands `p3` -> `p p p`. Such a field generation is not possible with `FORM` and `(p FORM)`.

**Comment by Luis-Henriquez-Perez** [comment]
> The only "downside" is that you have to write plain Elisp code. But I wouldn't even call this a disadvantage. The big advantage is that the snippets can be shared without also sharing custom element definitions, as long as your snippets rely only on basic Elisp.

I agree that it is nice be able to write the elisp code assuming that it's either very short of a very specific "one/few time case". However I'm beginning to suspect that there will be some lisp idioms that will become so repetitive that they'll warrant a custom element. I don't want to speak too soon though, I'll keep "watching" to see how it goes.

**Comment by minad** [comment]
> However I'm beginning to suspect that there will be some lisp idioms that will become so repetitive that they'll warrant a custom element.

Yes, this could happen. If we add user elements we should probably add the most general form 3. from above, since then you can translate to both 1. and 2.

**Comment by minad** [comment]
Added in https://github.com/minad/tempel/commit/91baf97c37c12f42c306e2f4330cdb4982e291db to work towards compatibility with Tempo (#18).
