### ISSUE TITLE
Option to wipe all cursors.

### ISSUE THREAD

**Issue by Gavinok** [minad/tempel#72]
There are multiple points where tempel will break causing left over cursors to stick around. Some way to cancel all cursors would really help recover from this without leaving cursors all over.

![tempel2](https://user-images.githubusercontent.com/34443260/194799024-4c5e679a-6647-42b8-aff3-a86220c5a2a6.gif)

**Comment by minad** [comment]
tempel-done

**Comment by Gavinok** [comment]
> tempel-done

That did not resolve the problem. After calling resolve done the issue remains.

**Comment by minad** [comment]
Okay, please create a minimal step-by-step example which I can try out starting from emacs -Q.

**Comment by minad** [comment]
I just committed https://github.com/minad/tempel/commit/95bec6b4aa138573cbaf15636321040c50ef817c which ensures that common failures during template expansion are handled more gracefully.

**Comment by Gavinok** [comment]
Latest commit has fixed this. Thanks @minad Keep up the great work
