### ISSUE TITLE
Question about Indentation

### ISSUE THREAD

**Issue by drcxd** [minad/tempel#73]
The following template:
```
(class "class " (p "ClassName&InheritanceList") n>
       "{" n>
       q n>
       "};" n>)
```
generates the following output:
```
class ClassName&InheritanceList
{
  
  };
```
My question is that why the closing curly brace is not indented as expected. By "expected", I mean the result I get if I execute `indent-according-to-mode` on the line contains the closing brace:
```
class ClassName&InheritanceList
{
  
};
```

**Comment by minad** [comment]
This works:

~~~
(class "class " (p "ClassName&InheritanceList") n
       "{" n>
       q n
       "};" n>)
~~~

You have to make sure that the `>` indentation calls happen at the right place. But I have no idea what the best pattern is. Maybe you can find some prepared Java Tempo templates somwhere.
