### ISSUE TITLE
Command for manual reloading

### ISSUE THREAD

**Issue by adrianadermon** [minad/tempel#74]
The `tempel-auto-reload` variable is obviously very useful when developing new templates. However, I have my dotfiles symlinked from a Git repo, and on Windows 11 Emacs doesn't seem able to detect changes to these symlinked files. This means that I have to restart Emacs to access the changes to my templates.

For this reason, I would find it very useful to have a command for manually reloading the tempate file.

**Comment by minad** [comment]
You can set tempel--path-templates to nil to force reloading. I don't
think we should add a separate command since it is not needed in most
scenarios.

**Comment by adrianadermon** [comment]
That works, thanks!
