### ISSUE TITLE
tempel-clojure 

### ISSUE THREAD

**Issue by mpenet** [minad/tempel#78]
Hi, 

Thanks for yet another very neat package.

Just a heads up: I created/will-add-more templates for clojure at https://github.com/mpenet/tempel-clojure. I also happen to maintain the clojure-snippets package for yas, I plan to port all of these templates over to tempel.
  
It's also packaged for melpa/straight.el consumption and hopefully would be available in a not too distant future. You can follow it there: https://github.com/melpa/melpa/pull/8282

**Comment by minad** [comment]
The discussion happens in #68.
