### ISSUE TITLE
Template data format

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [minad/tempel#8]
Right now the data structure of templates looks like:

`(MODE1 (TRIGGER1 ELEMENTS1) (TRIGGER2 ELEMENTS2)...MODE2 (TRIGGER1 ELEMENTS1...)`

The problem I have with this is that it is sort of difficult to manipulate/query/loop through. It's not a proper plist or an alist so we can't use `plist-get` or `alist-get` or the `map` library which is inconvenient. Moreover, we don't yet know whether this structure is the most appropriate considering you want "some dynamic facilities to provide mode specific or even context specific templates" as you mentioned in #3. So maybe a snippet is specified that loads based on a generic condition as opposed to a specific mode.

I propose this data is converted to a lists of plists upon loading. 

`((:mode MODE1 :trigger TRIGGER1 :elements ELEMENTS1) (:mode MODE2 :trigger TRIGGER1 :elements ELEMENTS2)...))`

This data is easily loopable/querable/filterable, etc.

**Comment by minad** [comment]
Currently the data structure is just a result of how these templates files are written. If we implement various configurable template sources/providers, the template providers should return a simple list of all templates which apply to the current context/mode. I think that is the most flexible design. Let's continue the discussion in #3.

**Comment by minad** [comment]
Let's keep this open. There are two more points which should be discussed:

* Do we need docstrings per template? Initially I had them but then I got annoyed writing them for small personal templates. But if we make this a fully fleshed out system, we need them I guess?
* Support binding templates to keys? Should this be configurable in the template file? I think not. To bind templates, simply use a define-key helper `(tempel-define-key map key template-name)`, which then calls `tempel-insert`.

**Comment by Luis-Henriquez-Perez** [comment]
> If we implement various configurable template sources/providers, the template providers should return a simple list of all templates which apply to the current context/mode. I think that is the most flexible design.

My point is that the most important objects are the templates themselves, but currently the structure is mode-centric (for example `(length tempel--templates)` is the number of modes specified not the number of templates). Instead of considering template as properties of a mode we should consider a mode as a property of a template.

If we used list of plists any future loops would basically be as simple as this--just replacing `mode` for any property we want.

```elisp
(dolist (template templates)
  (when-let (mode (plist-get template :mode))
    (when (derived-mode-p mode)
      ...)))
```

For example, suppose we gave each template a context. The loop remains trivial--essentially the same.

```
(let (result)
  (dolist (template templates)
    (when-let (context (plist-get template :context))
      (when (funcall context)
	(push template result)))))
```

But as it is now we always have to do this kind of thing every time we filter/query the templates.

```elisp
(let (result (templates tempel--templates))
    (while (and templates (symbolp (car templates)))
      (when (derived-mode-p (car templates))
        (push (seq-take-while #'consp (cdr templates)) result))
      (setq templates (seq-drop-while #'consp (cdr templates))))
    (apply #'append result))
```

**Comment by minad** [comment]
> My point is that the most important objects are the templates themselves, but currently the structure is mode-centric (for example (length tempel--templates) is the number of modes specified not the number of templates). Instead of considering template as properties of a mode we should consider a mode as a property of a template.

I prefer the current design to be honest. The point is - I want to categorize snippets by mode and I don't want to repeat myself a lot and write :mode everywhere. 

I argue that the two loops you've given above are both trivial. You need a loop anyways since we use `derived-mode-p` or some other context function. There would be a difference if the list could be a simple alist which could be queried with the `major-mode` and `alist-get`, but this is not the case due to mode derivatives.

**Comment by Luis-Henriquez-Perez** [comment]
> I prefer the current design to be honest. The point is - I want to categorize snippets by mode and I don't want to repeat myself a lot and write :mode everywhere.

Ok. I respect your decision.

> Support binding templates to keys?

I would let the user do this. I think there's plenty of `define-key` wrappers already and it's rather trivial. I consider it unnecessary, but not particularly harmful. So I don't have qualms about you adding it in.

I noticed you used an anonymous function to as the definition of the key. Perhaps defining an named function that inserts the template would be preferable. Speaking of which, I do want to point out that `tempo-define-key` defines an interactive function that inserts the template. I don't know if you want to also do this for `tempel-define-key`.

> Should this be configurable in the template file?

Seems out of scope to me.

> Do we need docstrings per template? Initially I had them but then I got annoyed writing them for small personal templates.

They are optional. `tempo-define-key` as I mentioned defined a function for each template that could be called to insert the template. If we go this route, then the docstring would make more sense.

**Comment by minad** [comment]
I added `temple-key` in https://github.com/minad/tempel/commit/e4839df53314ff0e4f89c7724d8a4239e359938f. What do you think?

**Comment by Luis-Henriquez-Perez** [comment]
> I added temple-key in e4839df. What do you think?

Looks good. I mentioned some thoughts I had on it above.

**Comment by minad** [comment]
Closing. I think the data format we have right now is good enough. As a  possible backward-compatible future extension, we could support keyword arguments, which specify additional metadata.

~~~ elisp
emacs-lisp-mode

(lambda
  :doc "Documentation"
  :alias lam 
  "(lambda (" p ")" n> r> ")")
~~~
