### ISSUE TITLE
Is it possible to show the candidate in corfu but without completing the snippet when name is completed?

### ISSUE THREAD

**Issue by wang1zhen** [minad/tempel#82]
Hi, when using the code in the readme,

```
(defun tempel-setup-capf ()
        ;; Add the Tempel Capf to `completion-at-point-functions'.
        ;; `tempel-expand' only triggers on exact matches. Alternatively use
        ;; `tempel-complete' if you want to see all matches, but then you
        ;; should also configure `tempel-trigger-prefix', such that Tempel
        ;; does not trigger too often when you don't expect it. NOTE: We add
        ;; `tempel-expand' *before* the main programming mode Capf, such
        ;; that it will be tried first.
        (setq-local completion-at-point-functions
                    (cons #'tempel-expand
                          completion-at-point-functions)))
```
the snnipet candidate is not shown in the corfu candidate:

![图片](https://user-images.githubusercontent.com/31798841/204430543-32ac91b6-53b9-4099-8820-174b57d71ef6.png)

However, when changed to =tempel-complete=, the candidate is shown, butit will be expanded instantly when the name is completed (when "today" is finished, it gets expanded to the snnipet):

![图片](https://user-images.githubusercontent.com/31798841/204430735-b4369ed8-56cc-45a9-b261-4ee6790d1117.png)

Is it possible to add the snippet candidate to corfu, but only expand it when `corfu-complete` is called?

**Comment by minad** [comment]
Each of these three Corfu setting combinations should work:

~~~
(setq corfu-on-exact-match 'quit
      corfu-preselect-first nil)

(setq corfu-on-exact-match nil
      corfu-preselect-first t)

(setq corfu-on-exact-match nil
      corfu-preselect-first nil)
~~~

Note that these settings apply to all of Corfu. You could make them buffer-local or try to enable them only during Tempel completion. Another good alternative is to set a `tempel-trigger-prefix`. I use `>`. Does this help?
