### ISSUE TITLE
SPC expands snippet

### ISSUE THREAD

**Issue by kresdjan** [minad/tempel#83]
I have not bound anything related to Temple, abbrev, Cape or Corfu (except s-SPC as separator). Yet if I type the name of template and hit SPC it expand the template. I can't figure out how to not make this happen. 

It happens in a `.glsl` file  in `glsl-mode` with is a C style mode. This is what I can learn from Help. 
```
SPC runs the command self-insert-command (found in global-map), which
is an interactive built-in function in ‘C source code’.
```

Is there a way to not have this trigger Tempel?

I have a very basic `init.el` but where are the only key mappings I've done and every thing related to Tempel, Corfu and Cape.
```lisp
(setq ns-command-modifier 'meta)
(setq ns-right-alternate-modifier 'super)
(setq ns-alternate-modifier 'none)
(setq ns-function-modifier 'hyper)

(keymap-global-set "C-c p d" 'cape-dabbrev)
(keymap-global-set "C-c p a" 'cape-abbrev)
(keymap-global-set "C-c p f" 'cape-file)
(keymap-global-set "s-SPC" 'corfu-insert-separator)

(require 'corfu)
(setq-local corfu-auto t
	    corfu-auto-delay 0
	    corfu-auto-prefix 2) 
(global-corfu-mode)

(corfu-popupinfo-mode)

(setq tab-always-indent 'complete)

(require 'tempel)
(global-tempel-abbrev-mode t)

(require 'cape)
(add-to-list 'completion-at-point-functions #'cape-dabbrev)
(add-to-list 'completion-at-point-functions #'cape-abbrev)
(add-to-list 'completion-at-point-functions #'cape-file)
```

**Comment by minad** [comment]
@kresdjan If you don't want SPC to expand, don't enable `global-tempel-abbrev-mode`.
