### ISSUE TITLE
Same field given by a previous one but not allowed to be jump into

### ISSUE THREAD

**Issue by linwaytin** [minad/tempel#84]
Thank you for this nice little package. I'm trying to move from yasnippet to this one. 

One question I have is this: For a snippet like the following:
```lisp
(measure-time > (p "start" start) " = high_resolution_clock::now();" n
	      > r
	      > (p "end" end) " = high_resolution_clock::now();" n
	      > "std::cout << \"The time for " (p "xxx") " is: \"<< " q "duration_cast<microseconds>(" (s end) "-" (s start) ").count() << \"(us)\" << std::endl;" n> )
```
The field `start` and `end` are saved and automatically inserted in `(s start)` and `(s end)` later, which won't be changed anymore. However, when inserting this snippet, the cursor can still jump to the position of `(s xxx)` with `M-}`. This is not necessary, and I'm curious if this behavior can be changed. Not a big problem, but sometimes a little bothering. 

Again, thanks for this and other great packages you made.

**Comment by minad** [comment]
You can simply write start instead of (s start).

**Comment by linwaytin** [comment]
Thank you.

**Comment by rynoV** [comment]
Fyi, this solution doesn't work if your named field is defined without a placeholder (e.g. with `(s start)` instead of `(p "start" start)`). It'll give the error: `Wrong type argument: char-or-string-p, nil`
