### ISSUE TITLE
Weird behavior when a (p "xxx") at the beginning of a new line from a region

### ISSUE THREAD

**Issue by linwaytin** [minad/tempel#85]
The snippet is as follows, used in c++ mode:
```lisp
(test-indent > "beginning;" n
             > r> 
             > (p "field") " " "first end line;" > n>
             )
```
Now for the following c++ code
```c++
  {
    some content;
  }
```
if I select `some content;` including the newline at the end (this would also be the result of `evil`'s `visual-line` mode), and `temple-insert` the above lisp, I expect the cursor is at the beginning the of placeholder (the character 'f' in this case). However, the cursor is at the beginning of the line like this (the cursor position is represented by '|')
```
  {
    beginning;
    some content; 
|   field first end line;
  }
```
Moreover, if I start to type, the whole line would immediately shift to the beginning. I feel it seems a result of the indentation mechanism together with the placeholder. If some other text is placed in front of the placeholder, the issue is gone. Also, if the next line is not `  }` of a different level, the issue does not appear.

**Comment by minad** [comment]
You should probably use > more carefully. I don't see a Tempel issue here.

**Comment by linwaytin** [comment]
I have tried different combinations of `>` here. Do you know how to make the template right in the aforementioned situation?

**Comment by minad** [comment]
No, I would have to experiment myself.
