### ISSUE TITLE
Templates for the Examples

### ISSUE THREAD

**Issue by Zaijab** [minad/tempel#86]
What are the templates for the examples given in the README file? I'm interested especially in the middle `enumerate` gif. 

Using ```(enumerate "\\begin{enumerate}\n\\item " r> n> "\\end{enumerate}")``` we may write a template which fills in the enumerate and one item, but I do not know how to insert another `\item` using the same template. I feel as though the same logic may be extended to a fast insertion of elements in `align` or `bmatrix` environments too.

**Comment by minad** [comment]
@Zaijab The items are not actually generated by Tempel but by Tex-mode.

**Comment by minad** [comment]
Btw, you may be more interested in cdlatex in case you are not yet familiar with that.

**Comment by Zaijab** [comment]
I understand, forgive my misunderstanding. Thank you for your swift reply.
