### ISSUE TITLE
`%` syntax element not working

### ISSUE THREAD

**Issue by rynoV** [minad/tempel#87]
With a template like `(t % "test")`, on a newline if I expand from "t" I would expect it to add another newline before inserting "test", but it only inserts "test". Same if I expand after typing "test test t" on a newline.

Another example: `(t "test" % "test")` expands to `testtest` on a newline.

**Comment by minad** [comment]
Sorry, this was a documentation mistake. The % and & elements are meant to introduce a newline if there is already text on your line, e.g., if you are writing prose.

**Comment by rynoV** [comment]
Ah okay, so `&` does what I was looking for, thanks!
