### ISSUE TITLE
Clarification about `(FORM ...)` extension

### ISSUE THREAD

**Issue by ft** [minad/tempel#88]
When trying to write a template that expands to a C/C++ style inclusion guard, I came across this:

- `(FORM ...) Other Lisp forms are evaluated. Named fields are lexically bound.`

I am using this extension all over the place. Excellent feature! But I don't understand the "Named fields are lexically bound." part.

How would one introduce a named field with this sort of expression?

My hope was to be able to evaluate some code and bind that to a symbol, that I could reuse in the rest of the template. Currently I am doing that with a `(p FORM name)` prompt:

```elisp
(guard
 "#ifndef " (p (ft/tempel:c-guard "INC_") c-guard) n
 "#define " c-guard n n p q n n
 "#endif /* " c-guard " */" n)
```

This works (the `ft/tempel:c-guard` function generates the macro name for the current buffer), but forces me to press more keys to finish up the expansion. Ideally I don't want any interaction here and just be dropped where the `p q` sequence indicates. Of course I could also call the function in three places, but it's a little expensive to run and doing so feels inelegant.

If the `(FORM ...)` extension could do this, that would be great, I just can't figure out (from the documentation) how to bind any field from these expressions. Any example would be appreciated.

**Comment by minad** [comment]
I think you could use the no-insert variant `(p FORM name t)`. Does this help?

**Comment by ft** [comment]
Yes, rewriting the template to this:

```elisp
(guard
 (p (ft/tempel:c-guard "INC_") c-guard t)
 "#ifndef " c-guard n
 "#define " c-guard n n p q n n
 "#endif /* " c-guard " */" n)
```

…works the way I prefer, thanks!

Still, though, could you clarify the part about the lexically bound named fields with the `(FORM ...)` extension? :)

**Comment by minad** [comment]
`p` can introduce a named field. The variable corresponding to the field is then bound when `FORM` is evaluated. Take a look at the examples.

**Comment by ft** [comment]
Ah, so it is only in conjunction with `p`, it cannot do it on its own. That's the missing piece, thanks.

**Comment by ft** [comment]
Yes, now that I understand the comment it's easy to see. What might have saved me the confusion would have been something along the lines of `Named fields, introduced by other constructs (such as p), are bound lexically while the form is evaluated`.

**Comment by minad** [comment]
Yes, that would be more clear.
