### ISSUE TITLE
void-variable tempel-map in doom emacs. 

### ISSUE THREAD

**Issue by anbanpillay** [minad/tempel#90]
I tried using Tempel in Doom eMacs and get this error: void-variable tempel-map. 
I used the configuration from the GitHub page.

**Comment by minad** [comment]
That's a Doom issue and must be fixed there by unpinning Compat.

**Comment by anbanpillay** [comment]
Thank you so much for your quick response. It is fixed. I really appreciate.

From: Daniel Mendler ***@***.***>
Date: Friday, 27 January 2023 at 17:40
To: minad/tempel ***@***.***>
Cc: anbanpillay ***@***.***>, Author ***@***.***>
Subject: Re: [minad/tempel] void-variable tempel-map in doom emacs. (Issue #90)

That's a Doom issue and must be fixed there by unpinning Compat.
