### ISSUE TITLE
[Suggestion] add a function that combines tempel-complete/expand and tempel-next

### ISSUE THREAD

**Issue by Ziqi-Yang** [minad/tempel#91]
I find it somewhat awkward to use different keys to complete and move next. Though different keys enable nested template completion, it is a bit niggling. I'd prefer another function that combines `tempel-complete` / `tempel-expand` and `tempel-next`. Like:
```elisp
(defun mk/tempel-complete-or-next ()
  (interactive)
  (if (not tempel--active)
    (call-interactively 'tempel-complete)
    (call-interactively 'tempel-next)))
```

**Comment by minad** [comment]
You can simply bind tempel-next in tempel-map to the same key as tempel-complete.
