### ISSUE TITLE
Using named field's value as prompt/default for other fields

### ISSUE THREAD

**Issue by kenranunderscore** [minad/tempel#96]
I hope this isn't answered anywhere in the issues yet; at least I didn't find anything except for #5 that looks similar. (I've also asked my question on reddit yesterday, but it seems to have drowned already; I'll update there if I learn anything here).

In Haskell, I often write the following:
```haskell
newtype Foo = Foo { unFoo :: Int }
```

Now with TempEL (I did this with yasnippet before) I'd like to achieve the following:
- Type `Foo` in the first position once, and have it fill in the other two `Foo`s
- Still jump to the 2nd and 3rd `Foo` and be able to change it, but *only there*, that is, without touching the respective other `Foo`s

I've tried:
- Use `(s name)` for the first occurrence, and `name` for the others -> it's just a value and I can't edit there
- Use `(s name)` for all the fields -> I can set all three values simultaneously from all positions
- Use `(p "FOO" name)` for the first one, and I was hoping I could use `(p name)` (i.e., have the value of `name` be the default/prompt value) for the others -> the 2nd and 3rd position values stay `FOO` here

I guess I'd have to use one of the form or ELisp variants, but I'm stuck. Can I do this in TempEL?

**Comment by minad** [comment]
As far as I know, Tempel doesn't support fields with dynamic default values, which can then be edited afterwards. Either fields are dynamic or they are editable. The reason for the current behavior is that the fields with default values may call functions with side effects or user interactions like completing-read or read-from-minibuffer. The best we can do for now is this:

~~~ lisp
(newtype "newtype " (s name) " = " name " { un" name " :: " (p "Int") " }")
~~~

As you noticed using placeholders doesn't work:

~~~ lisp
(newtype "newtype " (s name) " = " (p name) " { " (p (concat "un" name)) " :: " (p "Int") " }")
~~~

But we could consider adding support for such dynamically updated placeholders, which are not updated anymore after being edited.

~~~ lisp
(newtype "newtype " (s name) " = " (P name) " { " (P (concat "un" name)) " :: " (p "Int") " }")
~~~

**Comment by kenranunderscore** [comment]
Yes, the proposed feature is exactly what I'd love to use. I'd be okay with it not existing though, if it bloats the existing code base, as for my specific use case your first example template fits like 95% of the time; the other 5% it's not much work to quickly edit the accessor name. (A viable alternative (for me) would be to - instead of a template - write an Emacs command that prompts me for the three different parts and can use values I've previously entered to provide defaults.)

**Comment by minad** [comment]
You can already use a prompt - `(p (read-string ...) name)` instead of `(s name)`. I don't know how much it would complicate the code base. For me the main criterion is how widely a new feature would be required by templates. Furthermore I want to keep compatibility with Tempo.

**Comment by kenranunderscore** [comment]
Would you like me to close this or do you wish to wait for more opinions?

For my own part, I'm content, having successfully convinced myself that the variant with just a single named field leads to a simpler default case, which is also nice.

**Comment by minad** [comment]
Okay, good. Then we can close this for now. If you come up with many templates which would need the feature we can still revisit in the future.
